/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Web password login
         * @description Mini App clients do not use this — they send `tma <initData>` per request.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current viewer profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Departments by type */
        get: operations["listDepartments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dish catalog for the order editor */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order categories (типы заявок) */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders (paged, filtered)
         * @description Shop users see their own shop's orders; baker/admin see all.
         */
        get: operations["listOrders"];
        put?: never;
        /** Create an order (shop/admin) */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order by number */
        get: operations["getOrder"];
        /** Update an order (shop/admin; category never changes) */
        put: operations["updateOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft-cancel an order (idempotent) */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a cancelled order (idempotent) */
        post: operations["restoreOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle the favorite flag (admin) */
        patch: operations["setOrderFavorite"];
        trace?: never;
    };
    "/production": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Production journal (baker/admin) */
        get: operations["listProductionSheets"];
        put?: never;
        /**
         * Create a production sheet (baker/admin)
         * @description Fixes the batch: every selected order is saved on the sheet, items carry only deviations from the заявка (orders may have none).
         */
        post: operations["createProductionSheet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/production/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Production sheet with items */
        get: operations["getProductionSheet"];
        /**
         * Replace a sheet's batch and deviations
         * @description Values equal to the order quantity drop the deviation row; the sheet keeps its batch and lives until explicitly deleted, even with no deviations left.
         */
        put: operations["updateProductionSheet"];
        post?: never;
        /** Delete a sheet (facts fall back to the заявка) */
        delete: operations["deleteProductionSheet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dough calculation for several orders */
        get: operations["getBatchMonitor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dough calculation for one order (its category's codes) */
        get: operations["getOrderMonitor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/{id}/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dough calculation for one order and one ingredient code */
        get: operations["getOrderMonitorByProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (admin) */
        get: operations["listUsers"];
        put?: never;
        /** Create a user (admin; the only way — no self-registration) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /** Update a user (partial; password change is a reset) */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/admin/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All departments for user assignment (admin) */
        get: operations["listAdminDepartments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dish catalog with codes (admin) */
        get: operations["listDishes"];
        put?: never;
        /** Add a dish to the catalog */
        post: operations["createDish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dishes/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search iiko DISH products to add */
        get: operations["searchAvailableDishes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dishes/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder the whole catalog */
        put: operations["reorderDishes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dishes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a catalog dish */
        put: operations["updateDish"];
        post?: never;
        /** Remove a dish from the catalog */
        delete: operations["deleteDish"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an order category */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a category (code is immutable) */
        put: operations["updateCategory"];
        post?: never;
        /** Delete a category (fails while dishes reference it) */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Department: {
            /** Format: int64 */
            id: number;
            /** @example gagarina */
            code: string;
            /** @example Магазин Гагарина */
            name: string;
            /** @enum {string} */
            type: "shop" | "workshop";
        };
        Me: {
            role: string;
            /** Format: int64 */
            telegram_id: number;
            telegram_username: string;
            /** Format: int64 */
            department_id: number;
            department_code: string;
            department_name: string;
            department_type: string;
        };
        Category: {
            /** Format: int64 */
            id: number;
            /** @example bread */
            code: string;
            /**
             * @description Becomes part of the order number
             * @example Х
             */
            letter: string;
            /** @example Хлеб */
            name: string;
            /**
             * @description Must stay in sync with domain.CategoryColors and frontend lib/categories.js
             * @enum {string}
             */
            color: "amber" | "sky" | "violet" | "emerald" | "rose" | "stone";
            /** Format: int64 */
            sort_order: number;
            /** @description Dough codes used by /monitor for this category */
            monitor_codes: string[];
        };
        CategoryWrite: {
            code: string;
            letter: string;
            name: string;
            /** @enum {string} */
            color: "amber" | "sky" | "violet" | "emerald" | "rose" | "stone";
            /** Format: int64 */
            sort_order?: number;
            monitor_codes?: string[];
        };
        OrderItem: {
            code: string;
            product_name: string;
            quantity: number;
            reserved_quantity: number;
            /** @description quantity + reserved_quantity */
            production_quantity: number;
            /** @description Production fact; absent = baked as ordered */
            produced_quantity?: number | null;
            produced_reason?: string;
        };
        Comments: {
            general: string;
            items: {
                product_name: string;
                comment: string;
            }[];
        };
        HistoryItem: {
            /** @enum {string} */
            change_type: "added" | "updated" | "removed";
            product_code: string;
            product_name: string;
            old_quantity?: number | null;
            new_quantity?: number | null;
            old_reserved_quantity?: number | null;
            new_reserved_quantity?: number | null;
        };
        HistoryEntry: {
            /** Format: int64 */
            id: number;
            changed_by_username: string;
            /** @description RFC3339 */
            changed_at: string;
            items: components["schemas"]["HistoryItem"][];
        };
        Order: {
            id: string;
            /** @example Г.Х.08.07.26.001 */
            number: string;
            location: string;
            created_by_username: string;
            from_department?: components["schemas"]["Department"];
            to_department?: components["schemas"]["Department"];
            category?: components["schemas"]["Category"];
            items: components["schemas"]["OrderItem"][];
            /** @description RFC3339 */
            created_at: string;
            /** Format: date */
            fulfillment_date: string;
            /** @example /monitor Г.Х.08.07.26.001 */
            monitor_command: string;
            comments: components["schemas"]["Comments"];
            favorite: boolean;
            cancelled: boolean;
            cancelled_by_username?: string;
            /**
             * Format: int64
             * @description The sheet covering this order (an order has at most one)
             */
            production_sheet_id?: number | null;
            history?: components["schemas"]["HistoryEntry"][];
        };
        OrdersPage: {
            items: components["schemas"]["Order"][];
            page: number;
            limit: number;
            offset: number;
            /** Format: int64 */
            total: number;
            total_pages: number;
        };
        OrderWrite: {
            items: {
                product_name: string;
                quantity: number;
                reserved_quantity?: number;
            }[];
            /** Format: date */
            fulfillment_date?: string;
            /** Format: int64 */
            from_department_id?: number | null;
            /**
             * Format: int64
             * @description Required on create; ignored on update (category is immutable)
             */
            category_id?: number;
            comments?: components["schemas"]["Comments"];
        };
        DishCatalogItem: {
            code: string;
            name: string;
            /** @description Display group */
            theme: string;
            /** Format: int64 */
            category_id?: number | null;
            /** Format: int64 */
            sort_order: number;
        };
        Dish: components["schemas"]["DishCatalogItem"];
        DishWrite: {
            /** @description iiko product code */
            code: string;
            name: string;
            theme: string;
            /** Format: int64 */
            category_id?: number | null;
            /** Format: int64 */
            sort_order?: number;
        };
        AvailableDish: {
            code: string;
            name: string;
            unit: string;
        };
        ProductionItemWrite: {
            product_name: string;
            produced_quantity: number;
            /** @description Optional justification («подгорело» */
            reason?: string;
        };
        ProductionWrite: {
            /** @description The batch — every selected order, deviations optional per order */
            orders: {
                number: string;
                items: components["schemas"]["ProductionItemWrite"][];
            }[];
        };
        ProductionSheetItem: {
            order_number: string;
            product_name: string;
            produced_quantity: number;
            reason: string;
        };
        ProductionSheet: {
            /** Format: int64 */
            id: number;
            created_by_username: string;
            created_at: string;
            updated_at: string;
            /** @description The saved batch — every covered order, including those without deviations */
            order_numbers: string[];
            /**
             * Format: int64
             * @description Number of deviation rows
             */
            item_count: number;
            items?: components["schemas"]["ProductionSheetItem"][];
        };
        IngredientUsage: {
            product_code: string;
            product_name: string;
            unit: string;
            quantity: number;
        };
        IngredientReport: {
            ingredient: components["schemas"]["IngredientUsage"];
            breakdown: {
                order_item_code: string;
                order_item_name: string;
                order_item_quantity: number;
                ingredient_quantity: number;
            }[];
            /** @description The ingredient's own recipe expanded one level, scaled to the total */
            components?: components["schemas"]["IngredientUsage"][];
        };
        MonitorReport: {
            /** @description Monitored dough code */
            code: string;
            report: components["schemas"]["IngredientReport"];
        };
        OrderMonitor: {
            reports: components["schemas"]["MonitorReport"][];
            order: components["schemas"]["Order"];
        };
        BatchMonitor: {
            orders: {
                order: components["schemas"]["Order"];
                reports: components["schemas"]["MonitorReport"][];
            }[];
            total_reports: components["schemas"]["MonitorReport"][];
        };
        UserCreate: {
            username: string;
            /** Format: password */
            password: string;
            telegram_username?: string;
            /** @enum {string} */
            role: "admin" | "shop" | "baker" | "user";
            department_code?: string;
        };
        UserUpdate: {
            username?: string;
            /** @enum {string} */
            role?: "admin" | "shop" | "baker" | "user";
            department_code?: string;
            /** Format: password */
            password?: string;
        };
        User: {
            /** Format: int64 */
            id: number;
            username: string;
            telegram_username: string;
            /** Format: int64 */
            telegram_id?: number | null;
            /** @enum {string} */
            role: "admin" | "shop" | "baker" | "user";
            /** Format: int64 */
            department_id?: number | null;
            created_at: string;
            updated_at: string;
        };
    };
    responses: {
        /** @description Error with a safe user-facing message */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                };
            };
        };
    };
    parameters: {
        /** @description Order number, e.g. Г.Х.08.07.26.001 */
        OrderNumber: string;
        SheetID: number;
        UserID: number;
        DishCode: string;
        CategoryID: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Session issued (7-day TTL) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        /**
                         * Format: int64
                         * @description Unix seconds
                         */
                        expires_at: number;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role, telegram identity and optional department */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listDepartments: {
        parameters: {
            query?: {
                /** @description Omit for all departments. */
                type?: "shop" | "workshop";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Departments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog items in display order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishCatalogItem"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories sorted by sort_order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                from_department_id?: number;
                category_id?: number;
                fulfillment_date?: string;
                fulfillment_from?: string;
                fulfillment_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderWrite"];
            };
        };
        responses: {
            /** @description Created order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order number, e.g. Г.Х.08.07.26.001 */
                id: components["parameters"]["OrderNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The order with history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order number, e.g. Г.Х.08.07.26.001 */
                id: components["parameters"]["OrderNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderWrite"];
            };
        };
        responses: {
            /** @description Updated order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order number, e.g. Г.Х.08.07.26.001 */
                id: components["parameters"]["OrderNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cancelled order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    restoreOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order number, e.g. Г.Х.08.07.26.001 */
                id: components["parameters"]["OrderNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The restored order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setOrderFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order number, e.g. Г.Х.08.07.26.001 */
                id: components["parameters"]["OrderNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    favorite: boolean;
                };
            };
        };
        responses: {
            /** @description Updated order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listProductionSheets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sheets, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionSheet"][];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createProductionSheet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionWrite"];
            };
        };
        responses: {
            /** @description The created sheet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionSheet"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getProductionSheet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SheetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sheet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionSheet"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateProductionSheet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SheetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionWrite"];
            };
        };
        responses: {
            /** @description Updated sheet, or `id:0` when deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionSheet"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteProductionSheet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SheetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getBatchMonitor: {
        parameters: {
            query: {
                /** @description Order numbers (repeated param); duplicates are deduped. */
                orders: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-order reports plus totals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchMonitor"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getOrderMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order number, e.g. Г.Х.08.07.26.001 */
                id: components["parameters"]["OrderNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reports for every monitor code of the order's category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderMonitor"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getOrderMonitorByProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order number, e.g. Г.Х.08.07.26.001 */
                id: components["parameters"]["OrderNumber"];
                /** @description Ingredient (dough) code */
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single-code report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderMonitor"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Created user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listAdminDepartments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Departments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"][];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listDishes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dish"][];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createDish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishWrite"];
            };
        };
        responses: {
            /** @description Created dish */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dish"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    searchAvailableDishes: {
        parameters: {
            query?: {
                /** @description Name or code substring */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching iiko products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableDish"][];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    reorderDishes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    codes: string[];
                };
            };
        };
        responses: {
            /** @description Reordered */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    updateDish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["DishCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishWrite"];
            };
        };
        responses: {
            /** @description Updated dish */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dish"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteDish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["DishCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWrite"];
            };
        };
        responses: {
            /** @description Created category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWrite"];
            };
        };
        responses: {
            /** @description Updated category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
}
