// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const clientGetByID = `-- name: ClientGetByID :one
SELECT id, name, telegram_chat_id, phone, note, created_at, updated_at, deleted_at FROM clients
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ClientGetByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, clientGetByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TelegramChatID,
		&i.Phone,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const clientGetByTelegramChatID = `-- name: ClientGetByTelegramChatID :one
SELECT id, name, telegram_chat_id, phone, note, created_at, updated_at, deleted_at FROM clients
WHERE telegram_chat_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ClientGetByTelegramChatID(ctx context.Context, telegramChatID *int64) (Client, error) {
	row := q.db.QueryRow(ctx, clientGetByTelegramChatID, telegramChatID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TelegramChatID,
		&i.Phone,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const clientInsert = `-- name: ClientInsert :one
INSERT INTO clients (name, telegram_chat_id, phone, note)
VALUES ($1, $2, $3, $4)
RETURNING id, name, telegram_chat_id, phone, note, created_at, updated_at, deleted_at
`

type ClientInsertParams struct {
	Name           string  `json:"name"`
	TelegramChatID *int64  `json:"telegram_chat_id"`
	Phone          *string `json:"phone"`
	Note           *string `json:"note"`
}

func (q *Queries) ClientInsert(ctx context.Context, arg ClientInsertParams) (Client, error) {
	row := q.db.QueryRow(ctx, clientInsert,
		arg.Name,
		arg.TelegramChatID,
		arg.Phone,
		arg.Note,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TelegramChatID,
		&i.Phone,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const clientList = `-- name: ClientList :many
SELECT id, name, telegram_chat_id, phone, note, created_at, updated_at, deleted_at FROM clients
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ClientList(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, clientList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TelegramChatID,
			&i.Phone,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clientSoftDelete = `-- name: ClientSoftDelete :exec
UPDATE clients SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ClientSoftDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clientSoftDelete, id)
	return err
}

const clientUpdate = `-- name: ClientUpdate :one
UPDATE clients
SET name = $2, phone = $3, note = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, telegram_chat_id, phone, note, created_at, updated_at, deleted_at
`

type ClientUpdateParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Phone *string   `json:"phone"`
	Note  *string   `json:"note"`
}

func (q *Queries) ClientUpdate(ctx context.Context, arg ClientUpdateParams) (Client, error) {
	row := q.db.QueryRow(ctx, clientUpdate,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Note,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TelegramChatID,
		&i.Phone,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
