// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dough.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const doughCalcComputeTotals = `-- name: DoughCalcComputeTotals :many
SELECT
    tci.ingredient_id  AS dough_ingredient_id,
    i.name             AS dough_name,
    tci.unit           AS dough_unit,
    SUM(oi.quantity * (tci.net_qty / tc.yield_qty)) AS total_dough
FROM order_items oi
JOIN orders o     ON o.id = oi.order_id
JOIN products p   ON p.id = oi.product_id
JOIN LATERAL (
    SELECT id, yield_qty
    FROM tech_cards
    WHERE product_id = oi.product_id
      AND deleted_at IS NULL
      AND valid_from <= o.order_date
      AND (valid_to IS NULL OR valid_to >= o.order_date)
    ORDER BY version DESC
    LIMIT 1
) tc ON true
JOIN tech_card_items tci ON tci.tech_card_id = tc.id
JOIN ingredients i       ON i.id = tci.ingredient_id
                         AND i.is_dough = true
                         AND i.deleted_at IS NULL
WHERE o.order_date = $1
  AND o.status IN ('confirmed', 'parsed')
  AND o.deleted_at IS NULL
GROUP BY tci.ingredient_id, i.name, tci.unit
ORDER BY i.name
`

type DoughCalcComputeTotalsRow struct {
	DoughIngredientID uuid.UUID `json:"dough_ingredient_id"`
	DoughName         string    `json:"dough_name"`
	DoughUnit         string    `json:"dough_unit"`
	TotalDough        int64     `json:"total_dough"`
}

func (q *Queries) DoughCalcComputeTotals(ctx context.Context, orderDate string) ([]DoughCalcComputeTotalsRow, error) {
	rows, err := q.db.Query(ctx, doughCalcComputeTotals, orderDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoughCalcComputeTotalsRow{}
	for rows.Next() {
		var i DoughCalcComputeTotalsRow
		if err := rows.Scan(
			&i.DoughIngredientID,
			&i.DoughName,
			&i.DoughUnit,
			&i.TotalDough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doughCalcGetByDate = `-- name: DoughCalcGetByDate :many
SELECT dc.id, dc.kitchen_id, dc.calc_date, dc.dough_ingredient_id, dc.total_qty, dc.unit, dc.source, dc.created_at,
       i.name AS ingredient_name,
       k.name AS kitchen_name
FROM dough_calculations dc
JOIN ingredients i ON i.id = dc.dough_ingredient_id
LEFT JOIN kitchens k ON k.id = dc.kitchen_id
WHERE dc.calc_date = $1
ORDER BY k.name NULLS FIRST, i.name
`

type DoughCalcGetByDateRow struct {
	ID                uuid.UUID  `json:"id"`
	KitchenID         *uuid.UUID `json:"kitchen_id"`
	CalcDate          string     `json:"calc_date"`
	DoughIngredientID uuid.UUID  `json:"dough_ingredient_id"`
	TotalQty          float64    `json:"total_qty"`
	Unit              string     `json:"unit"`
	Source            string     `json:"source"`
	CreatedAt         time.Time  `json:"created_at"`
	IngredientName    string     `json:"ingredient_name"`
	KitchenName       *string    `json:"kitchen_name"`
}

func (q *Queries) DoughCalcGetByDate(ctx context.Context, calcDate string) ([]DoughCalcGetByDateRow, error) {
	rows, err := q.db.Query(ctx, doughCalcGetByDate, calcDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoughCalcGetByDateRow{}
	for rows.Next() {
		var i DoughCalcGetByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.KitchenID,
			&i.CalcDate,
			&i.DoughIngredientID,
			&i.TotalQty,
			&i.Unit,
			&i.Source,
			&i.CreatedAt,
			&i.IngredientName,
			&i.KitchenName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doughCalcInsert = `-- name: DoughCalcInsert :one
INSERT INTO dough_calculations (kitchen_id, calc_date, dough_ingredient_id, total_qty, unit, source)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kitchen_id, calc_date, dough_ingredient_id, total_qty, unit, source, created_at
`

type DoughCalcInsertParams struct {
	KitchenID         *uuid.UUID `json:"kitchen_id"`
	CalcDate          string     `json:"calc_date"`
	DoughIngredientID uuid.UUID  `json:"dough_ingredient_id"`
	TotalQty          float64    `json:"total_qty"`
	Unit              string     `json:"unit"`
	Source            string     `json:"source"`
}

func (q *Queries) DoughCalcInsert(ctx context.Context, arg DoughCalcInsertParams) (DoughCalculation, error) {
	row := q.db.QueryRow(ctx, doughCalcInsert,
		arg.KitchenID,
		arg.CalcDate,
		arg.DoughIngredientID,
		arg.TotalQty,
		arg.Unit,
		arg.Source,
	)
	var i DoughCalculation
	err := row.Scan(
		&i.ID,
		&i.KitchenID,
		&i.CalcDate,
		&i.DoughIngredientID,
		&i.TotalQty,
		&i.Unit,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const doughCalcItemDeleteByCalc = `-- name: DoughCalcItemDeleteByCalc :exec
DELETE FROM dough_calculation_items WHERE calculation_id = $1
`

func (q *Queries) DoughCalcItemDeleteByCalc(ctx context.Context, calculationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, doughCalcItemDeleteByCalc, calculationID)
	return err
}

const doughCalcItemInsert = `-- name: DoughCalcItemInsert :one
INSERT INTO dough_calculation_items
    (calculation_id, order_item_id, product_id, tech_card_id, quantity, dough_qty, unit)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, calculation_id, order_item_id, product_id, tech_card_id, quantity, dough_qty, unit, created_at
`

type DoughCalcItemInsertParams struct {
	CalculationID uuid.UUID `json:"calculation_id"`
	OrderItemID   uuid.UUID `json:"order_item_id"`
	ProductID     uuid.UUID `json:"product_id"`
	TechCardID    uuid.UUID `json:"tech_card_id"`
	Quantity      float64   `json:"quantity"`
	DoughQty      float64   `json:"dough_qty"`
	Unit          string    `json:"unit"`
}

func (q *Queries) DoughCalcItemInsert(ctx context.Context, arg DoughCalcItemInsertParams) (DoughCalculationItem, error) {
	row := q.db.QueryRow(ctx, doughCalcItemInsert,
		arg.CalculationID,
		arg.OrderItemID,
		arg.ProductID,
		arg.TechCardID,
		arg.Quantity,
		arg.DoughQty,
		arg.Unit,
	)
	var i DoughCalculationItem
	err := row.Scan(
		&i.ID,
		&i.CalculationID,
		&i.OrderItemID,
		&i.ProductID,
		&i.TechCardID,
		&i.Quantity,
		&i.DoughQty,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}

const doughCalcItemListByCalc = `-- name: DoughCalcItemListByCalc :many
SELECT dci.id, dci.calculation_id, dci.order_item_id, dci.product_id, dci.tech_card_id, dci.quantity, dci.dough_qty, dci.unit, dci.created_at, p.name AS product_name
FROM dough_calculation_items dci
JOIN products p ON p.id = dci.product_id
WHERE dci.calculation_id = $1
ORDER BY p.name
`

type DoughCalcItemListByCalcRow struct {
	ID            uuid.UUID `json:"id"`
	CalculationID uuid.UUID `json:"calculation_id"`
	OrderItemID   uuid.UUID `json:"order_item_id"`
	ProductID     uuid.UUID `json:"product_id"`
	TechCardID    uuid.UUID `json:"tech_card_id"`
	Quantity      float64   `json:"quantity"`
	DoughQty      float64   `json:"dough_qty"`
	Unit          string    `json:"unit"`
	CreatedAt     time.Time `json:"created_at"`
	ProductName   string    `json:"product_name"`
}

func (q *Queries) DoughCalcItemListByCalc(ctx context.Context, calculationID uuid.UUID) ([]DoughCalcItemListByCalcRow, error) {
	rows, err := q.db.Query(ctx, doughCalcItemListByCalc, calculationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoughCalcItemListByCalcRow{}
	for rows.Next() {
		var i DoughCalcItemListByCalcRow
		if err := rows.Scan(
			&i.ID,
			&i.CalculationID,
			&i.OrderItemID,
			&i.ProductID,
			&i.TechCardID,
			&i.Quantity,
			&i.DoughQty,
			&i.Unit,
			&i.CreatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
