// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const ingredientGetByID = `-- name: IngredientGetByID :one
SELECT id, iiko_id, name, unit, is_dough, created_at, updated_at, deleted_at FROM ingredients
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) IngredientGetByID(ctx context.Context, id uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, ingredientGetByID, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.IsDough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ingredientGetByIikoID = `-- name: IngredientGetByIikoID :one
SELECT id, iiko_id, name, unit, is_dough, created_at, updated_at, deleted_at FROM ingredients
WHERE iiko_id = $1 AND deleted_at IS NULL
`

func (q *Queries) IngredientGetByIikoID(ctx context.Context, iikoID *string) (Ingredient, error) {
	row := q.db.QueryRow(ctx, ingredientGetByIikoID, iikoID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.IsDough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ingredientList = `-- name: IngredientList :many
SELECT id, iiko_id, name, unit, is_dough, created_at, updated_at, deleted_at FROM ingredients
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) IngredientList(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, ingredientList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.IikoID,
			&i.Name,
			&i.Unit,
			&i.IsDough,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ingredientListDough = `-- name: IngredientListDough :many
SELECT id, iiko_id, name, unit, is_dough, created_at, updated_at, deleted_at FROM ingredients
WHERE is_dough = true AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) IngredientListDough(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, ingredientListDough)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.IikoID,
			&i.Name,
			&i.Unit,
			&i.IsDough,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ingredientUpsert = `-- name: IngredientUpsert :one
INSERT INTO ingredients (iiko_id, name, unit, is_dough)
VALUES ($1, $2, $3, $4)
ON CONFLICT (iiko_id) DO UPDATE
    SET name = EXCLUDED.name,
        unit = EXCLUDED.unit,
        is_dough = EXCLUDED.is_dough,
        updated_at = now(),
        deleted_at = NULL
RETURNING id, iiko_id, name, unit, is_dough, created_at, updated_at, deleted_at
`

type IngredientUpsertParams struct {
	IikoID  *string `json:"iiko_id"`
	Name    string  `json:"name"`
	Unit    string  `json:"unit"`
	IsDough bool    `json:"is_dough"`
}

func (q *Queries) IngredientUpsert(ctx context.Context, arg IngredientUpsertParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, ingredientUpsert,
		arg.IikoID,
		arg.Name,
		arg.Unit,
		arg.IsDough,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.IsDough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
