// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kitchens.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const kitchenGetByID = `-- name: KitchenGetByID :one
SELECT id, name, address, iiko_id, created_at, updated_at, deleted_at FROM kitchens
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) KitchenGetByID(ctx context.Context, id uuid.UUID) (Kitchen, error) {
	row := q.db.QueryRow(ctx, kitchenGetByID, id)
	var i Kitchen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.IikoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const kitchenGetByIikoID = `-- name: KitchenGetByIikoID :one
SELECT id, name, address, iiko_id, created_at, updated_at, deleted_at FROM kitchens
WHERE iiko_id = $1 AND deleted_at IS NULL
`

func (q *Queries) KitchenGetByIikoID(ctx context.Context, iikoID *string) (Kitchen, error) {
	row := q.db.QueryRow(ctx, kitchenGetByIikoID, iikoID)
	var i Kitchen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.IikoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const kitchenInsert = `-- name: KitchenInsert :one
INSERT INTO kitchens (name, address, iiko_id)
VALUES ($1, $2, $3)
RETURNING id, name, address, iiko_id, created_at, updated_at, deleted_at
`

type KitchenInsertParams struct {
	Name    string  `json:"name"`
	Address *string `json:"address"`
	IikoID  *string `json:"iiko_id"`
}

func (q *Queries) KitchenInsert(ctx context.Context, arg KitchenInsertParams) (Kitchen, error) {
	row := q.db.QueryRow(ctx, kitchenInsert, arg.Name, arg.Address, arg.IikoID)
	var i Kitchen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.IikoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const kitchenList = `-- name: KitchenList :many
SELECT id, name, address, iiko_id, created_at, updated_at, deleted_at FROM kitchens
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) KitchenList(ctx context.Context) ([]Kitchen, error) {
	rows, err := q.db.Query(ctx, kitchenList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kitchen{}
	for rows.Next() {
		var i Kitchen
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.IikoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kitchenSoftDelete = `-- name: KitchenSoftDelete :exec
UPDATE kitchens SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) KitchenSoftDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, kitchenSoftDelete, id)
	return err
}

const kitchenUpdate = `-- name: KitchenUpdate :one
UPDATE kitchens
SET name = $2, address = $3, iiko_id = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, address, iiko_id, created_at, updated_at, deleted_at
`

type KitchenUpdateParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Address *string   `json:"address"`
	IikoID  *string   `json:"iiko_id"`
}

func (q *Queries) KitchenUpdate(ctx context.Context, arg KitchenUpdateParams) (Kitchen, error) {
	row := q.db.QueryRow(ctx, kitchenUpdate,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.IikoID,
	)
	var i Kitchen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.IikoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
