// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID        int64     `json:"id"`
	TableName string    `json:"table_name"`
	RowID     uuid.UUID `json:"row_id"`
	Operation string    `json:"operation"`
	ChangedAt time.Time `json:"changed_at"`
	ChangedBy *string   `json:"changed_by"`
	OldData   any       `json:"old_data"`
	NewData   any       `json:"new_data"`
}

type Client struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	TelegramChatID *int64     `json:"telegram_chat_id"`
	Phone          *string    `json:"phone"`
	Note           *string    `json:"note"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
}

type DoughCalculation struct {
	ID                uuid.UUID  `json:"id"`
	KitchenID         *uuid.UUID `json:"kitchen_id"`
	CalcDate          string     `json:"calc_date"`
	DoughIngredientID uuid.UUID  `json:"dough_ingredient_id"`
	TotalQty          float64    `json:"total_qty"`
	Unit              string     `json:"unit"`
	Source            string     `json:"source"`
	CreatedAt         time.Time  `json:"created_at"`
}

type DoughCalculationItem struct {
	ID            uuid.UUID `json:"id"`
	CalculationID uuid.UUID `json:"calculation_id"`
	OrderItemID   uuid.UUID `json:"order_item_id"`
	ProductID     uuid.UUID `json:"product_id"`
	TechCardID    uuid.UUID `json:"tech_card_id"`
	Quantity      float64   `json:"quantity"`
	DoughQty      float64   `json:"dough_qty"`
	Unit          string    `json:"unit"`
	CreatedAt     time.Time `json:"created_at"`
}

type Ingredient struct {
	ID        uuid.UUID  `json:"id"`
	IikoID    *string    `json:"iiko_id"`
	Name      string     `json:"name"`
	Unit      string     `json:"unit"`
	IsDough   bool       `json:"is_dough"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Kitchen struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Address   *string    `json:"address"`
	IikoID    *string    `json:"iiko_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Order struct {
	ID                uuid.UUID  `json:"id"`
	ClientID          uuid.UUID  `json:"client_id"`
	KitchenID         *uuid.UUID `json:"kitchen_id"`
	TelegramChatID    *int64     `json:"telegram_chat_id"`
	TelegramMessageID *int64     `json:"telegram_message_id"`
	OrderDate         string     `json:"order_date"`
	Status            string     `json:"status"`
	RawText           *string    `json:"raw_text"`
	Note              *string    `json:"note"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	DeletedAt         *time.Time `json:"deleted_at"`
}

type OrderItem struct {
	ID        uuid.UUID `json:"id"`
	OrderID   uuid.UUID `json:"order_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  float64   `json:"quantity"`
	Unit      string    `json:"unit"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Product struct {
	ID        uuid.UUID  `json:"id"`
	IikoID    *string    `json:"iiko_id"`
	Name      string     `json:"name"`
	Unit      string     `json:"unit"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type TechCard struct {
	ID        uuid.UUID  `json:"id"`
	ProductID uuid.UUID  `json:"product_id"`
	Version   int32      `json:"version"`
	Source    string     `json:"source"`
	SourceRef *string    `json:"source_ref"`
	YieldQty  float64    `json:"yield_qty"`
	YieldUnit string     `json:"yield_unit"`
	ValidFrom time.Time  `json:"valid_from"`
	ValidTo   *time.Time `json:"valid_to"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type TechCardItem struct {
	ID           uuid.UUID `json:"id"`
	TechCardID   uuid.UUID `json:"tech_card_id"`
	IngredientID uuid.UUID `json:"ingredient_id"`
	GrossQty     float64   `json:"gross_qty"`
	NetQty       float64   `json:"net_qty"`
	Unit         string    `json:"unit"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
