// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const orderGetByID = `-- name: OrderGetByID :one
SELECT id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at, deleted_at FROM orders
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) OrderGetByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, orderGetByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.KitchenID,
		&i.TelegramChatID,
		&i.TelegramMessageID,
		&i.OrderDate,
		&i.Status,
		&i.RawText,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const orderInsert = `-- name: OrderInsert :one
INSERT INTO orders (client_id, kitchen_id, telegram_chat_id, telegram_message_id,
                    order_date, status, raw_text, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at, deleted_at
`

type OrderInsertParams struct {
	ClientID          uuid.UUID  `json:"client_id"`
	KitchenID         *uuid.UUID `json:"kitchen_id"`
	TelegramChatID    *int64     `json:"telegram_chat_id"`
	TelegramMessageID *int64     `json:"telegram_message_id"`
	OrderDate         string     `json:"order_date"`
	Status            string     `json:"status"`
	RawText           *string    `json:"raw_text"`
	Note              *string    `json:"note"`
}

func (q *Queries) OrderInsert(ctx context.Context, arg OrderInsertParams) (Order, error) {
	row := q.db.QueryRow(ctx, orderInsert,
		arg.ClientID,
		arg.KitchenID,
		arg.TelegramChatID,
		arg.TelegramMessageID,
		arg.OrderDate,
		arg.Status,
		arg.RawText,
		arg.Note,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.KitchenID,
		&i.TelegramChatID,
		&i.TelegramMessageID,
		&i.OrderDate,
		&i.Status,
		&i.RawText,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const orderItemDeleteByOrder = `-- name: OrderItemDeleteByOrder :exec
DELETE FROM order_items WHERE order_id = $1
`

func (q *Queries) OrderItemDeleteByOrder(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, orderItemDeleteByOrder, orderID)
	return err
}

const orderItemInsert = `-- name: OrderItemInsert :one
INSERT INTO order_items (order_id, product_id, quantity, unit)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, unit, created_at, updated_at
`

type OrderItemInsertParams struct {
	OrderID   uuid.UUID `json:"order_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  float64   `json:"quantity"`
	Unit      string    `json:"unit"`
}

func (q *Queries) OrderItemInsert(ctx context.Context, arg OrderItemInsertParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, orderItemInsert,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Unit,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const orderItemListByOrder = `-- name: OrderItemListByOrder :many
SELECT oi.id, oi.order_id, oi.product_id, oi.quantity, oi.unit, oi.created_at, oi.updated_at, p.name AS product_name
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = $1
ORDER BY p.name
`

type OrderItemListByOrderRow struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	ProductID   uuid.UUID `json:"product_id"`
	Quantity    float64   `json:"quantity"`
	Unit        string    `json:"unit"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ProductName string    `json:"product_name"`
}

func (q *Queries) OrderItemListByOrder(ctx context.Context, orderID uuid.UUID) ([]OrderItemListByOrderRow, error) {
	rows, err := q.db.Query(ctx, orderItemListByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItemListByOrderRow{}
	for rows.Next() {
		var i OrderItemListByOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderListByDate = `-- name: OrderListByDate :many
SELECT id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at, deleted_at FROM orders
WHERE order_date = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) OrderListByDate(ctx context.Context, orderDate string) ([]Order, error) {
	rows, err := q.db.Query(ctx, orderListByDate, orderDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.KitchenID,
			&i.TelegramChatID,
			&i.TelegramMessageID,
			&i.OrderDate,
			&i.Status,
			&i.RawText,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderListByDateAndStatus = `-- name: OrderListByDateAndStatus :many
SELECT id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at, deleted_at FROM orders
WHERE order_date = $1 AND status = $2 AND deleted_at IS NULL
ORDER BY created_at
`

type OrderListByDateAndStatusParams struct {
	OrderDate string `json:"order_date"`
	Status    string `json:"status"`
}

func (q *Queries) OrderListByDateAndStatus(ctx context.Context, arg OrderListByDateAndStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, orderListByDateAndStatus, arg.OrderDate, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.KitchenID,
			&i.TelegramChatID,
			&i.TelegramMessageID,
			&i.OrderDate,
			&i.Status,
			&i.RawText,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderSoftDelete = `-- name: OrderSoftDelete :exec
UPDATE orders SET deleted_at = now(), status = 'cancelled'
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) OrderSoftDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, orderSoftDelete, id)
	return err
}

const orderUpdateStatus = `-- name: OrderUpdateStatus :one
UPDATE orders SET status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at, deleted_at
`

type OrderUpdateStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) OrderUpdateStatus(ctx context.Context, arg OrderUpdateStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, orderUpdateStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.KitchenID,
		&i.TelegramChatID,
		&i.TelegramMessageID,
		&i.OrderDate,
		&i.Status,
		&i.RawText,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
