// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const productGetByID = `-- name: ProductGetByID :one
SELECT id, iiko_id, name, unit, created_at, updated_at, deleted_at FROM products
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ProductGetByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, productGetByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const productGetByIikoID = `-- name: ProductGetByIikoID :one
SELECT id, iiko_id, name, unit, created_at, updated_at, deleted_at FROM products
WHERE iiko_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ProductGetByIikoID(ctx context.Context, iikoID *string) (Product, error) {
	row := q.db.QueryRow(ctx, productGetByIikoID, iikoID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const productList = `-- name: ProductList :many
SELECT id, iiko_id, name, unit, created_at, updated_at, deleted_at FROM products
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ProductList(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, productList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.IikoID,
			&i.Name,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productUpsert = `-- name: ProductUpsert :one
INSERT INTO products (iiko_id, name, unit)
VALUES ($1, $2, $3)
ON CONFLICT (iiko_id) DO UPDATE
    SET name = EXCLUDED.name,
        unit = EXCLUDED.unit,
        updated_at = now(),
        deleted_at = NULL
RETURNING id, iiko_id, name, unit, created_at, updated_at, deleted_at
`

type ProductUpsertParams struct {
	IikoID *string `json:"iiko_id"`
	Name   string  `json:"name"`
	Unit   string  `json:"unit"`
}

func (q *Queries) ProductUpsert(ctx context.Context, arg ProductUpsertParams) (Product, error) {
	row := q.db.QueryRow(ctx, productUpsert, arg.IikoID, arg.Name, arg.Unit)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
