// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClientGetByID(ctx context.Context, id uuid.UUID) (Client, error)
	ClientGetByTelegramChatID(ctx context.Context, telegramChatID *int64) (Client, error)
	ClientInsert(ctx context.Context, arg ClientInsertParams) (Client, error)
	ClientList(ctx context.Context) ([]Client, error)
	ClientSoftDelete(ctx context.Context, id uuid.UUID) error
	ClientUpdate(ctx context.Context, arg ClientUpdateParams) (Client, error)
	DoughCalcComputeTotals(ctx context.Context, orderDate string) ([]DoughCalcComputeTotalsRow, error)
	DoughCalcGetByDate(ctx context.Context, calcDate string) ([]DoughCalcGetByDateRow, error)
	DoughCalcInsert(ctx context.Context, arg DoughCalcInsertParams) (DoughCalculation, error)
	DoughCalcItemDeleteByCalc(ctx context.Context, calculationID uuid.UUID) error
	DoughCalcItemInsert(ctx context.Context, arg DoughCalcItemInsertParams) (DoughCalculationItem, error)
	DoughCalcItemListByCalc(ctx context.Context, calculationID uuid.UUID) ([]DoughCalcItemListByCalcRow, error)
	IngredientGetByID(ctx context.Context, id uuid.UUID) (Ingredient, error)
	IngredientGetByIikoID(ctx context.Context, iikoID *string) (Ingredient, error)
	IngredientList(ctx context.Context) ([]Ingredient, error)
	IngredientListDough(ctx context.Context) ([]Ingredient, error)
	IngredientUpsert(ctx context.Context, arg IngredientUpsertParams) (Ingredient, error)
	KitchenGetByID(ctx context.Context, id uuid.UUID) (Kitchen, error)
	KitchenGetByIikoID(ctx context.Context, iikoID *string) (Kitchen, error)
	KitchenInsert(ctx context.Context, arg KitchenInsertParams) (Kitchen, error)
	KitchenList(ctx context.Context) ([]Kitchen, error)
	KitchenSoftDelete(ctx context.Context, id uuid.UUID) error
	KitchenUpdate(ctx context.Context, arg KitchenUpdateParams) (Kitchen, error)
	OrderGetByID(ctx context.Context, id uuid.UUID) (Order, error)
	OrderInsert(ctx context.Context, arg OrderInsertParams) (Order, error)
	OrderItemDeleteByOrder(ctx context.Context, orderID uuid.UUID) error
	OrderItemInsert(ctx context.Context, arg OrderItemInsertParams) (OrderItem, error)
	OrderItemListByOrder(ctx context.Context, orderID uuid.UUID) ([]OrderItemListByOrderRow, error)
	OrderListByDate(ctx context.Context, orderDate string) ([]Order, error)
	OrderListByDateAndStatus(ctx context.Context, arg OrderListByDateAndStatusParams) ([]Order, error)
	OrderSoftDelete(ctx context.Context, id uuid.UUID) error
	OrderUpdateStatus(ctx context.Context, arg OrderUpdateStatusParams) (Order, error)
	ProductGetByID(ctx context.Context, id uuid.UUID) (Product, error)
	ProductGetByIikoID(ctx context.Context, iikoID *string) (Product, error)
	ProductList(ctx context.Context) ([]Product, error)
	ProductUpsert(ctx context.Context, arg ProductUpsertParams) (Product, error)
	TechCardGetActive(ctx context.Context, arg TechCardGetActiveParams) (TechCard, error)
	TechCardGetByID(ctx context.Context, id uuid.UUID) (TechCard, error)
	TechCardInsert(ctx context.Context, arg TechCardInsertParams) (TechCard, error)
	TechCardItemDeleteByCard(ctx context.Context, techCardID uuid.UUID) error
	TechCardItemInsert(ctx context.Context, arg TechCardItemInsertParams) (TechCardItem, error)
	TechCardItemListByCard(ctx context.Context, techCardID uuid.UUID) ([]TechCardItemListByCardRow, error)
	TechCardItemListDoughByCard(ctx context.Context, techCardID uuid.UUID) ([]TechCardItemListDoughByCardRow, error)
	TechCardListByProduct(ctx context.Context, productID uuid.UUID) ([]TechCard, error)
	TechCardSoftDelete(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
