// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tech_cards.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const techCardGetActive = `-- name: TechCardGetActive :one
SELECT id, product_id, version, source, source_ref, yield_qty, yield_unit, valid_from, valid_to, created_at, updated_at, deleted_at FROM tech_cards
WHERE product_id = $1
  AND deleted_at IS NULL
  AND valid_from <= $2
  AND (valid_to IS NULL OR valid_to >= $2)
ORDER BY version DESC
LIMIT 1
`

type TechCardGetActiveParams struct {
	ProductID uuid.UUID `json:"product_id"`
	ValidFrom time.Time `json:"valid_from"`
}

func (q *Queries) TechCardGetActive(ctx context.Context, arg TechCardGetActiveParams) (TechCard, error) {
	row := q.db.QueryRow(ctx, techCardGetActive, arg.ProductID, arg.ValidFrom)
	var i TechCard
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Version,
		&i.Source,
		&i.SourceRef,
		&i.YieldQty,
		&i.YieldUnit,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const techCardGetByID = `-- name: TechCardGetByID :one
SELECT id, product_id, version, source, source_ref, yield_qty, yield_unit, valid_from, valid_to, created_at, updated_at, deleted_at FROM tech_cards
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TechCardGetByID(ctx context.Context, id uuid.UUID) (TechCard, error) {
	row := q.db.QueryRow(ctx, techCardGetByID, id)
	var i TechCard
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Version,
		&i.Source,
		&i.SourceRef,
		&i.YieldQty,
		&i.YieldUnit,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const techCardInsert = `-- name: TechCardInsert :one
INSERT INTO tech_cards (product_id, version, source, source_ref, yield_qty, yield_unit, valid_from, valid_to)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, product_id, version, source, source_ref, yield_qty, yield_unit, valid_from, valid_to, created_at, updated_at, deleted_at
`

type TechCardInsertParams struct {
	ProductID uuid.UUID  `json:"product_id"`
	Version   int32      `json:"version"`
	Source    string     `json:"source"`
	SourceRef *string    `json:"source_ref"`
	YieldQty  float64    `json:"yield_qty"`
	YieldUnit string     `json:"yield_unit"`
	ValidFrom time.Time  `json:"valid_from"`
	ValidTo   *time.Time `json:"valid_to"`
}

func (q *Queries) TechCardInsert(ctx context.Context, arg TechCardInsertParams) (TechCard, error) {
	row := q.db.QueryRow(ctx, techCardInsert,
		arg.ProductID,
		arg.Version,
		arg.Source,
		arg.SourceRef,
		arg.YieldQty,
		arg.YieldUnit,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i TechCard
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Version,
		&i.Source,
		&i.SourceRef,
		&i.YieldQty,
		&i.YieldUnit,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const techCardItemDeleteByCard = `-- name: TechCardItemDeleteByCard :exec
DELETE FROM tech_card_items WHERE tech_card_id = $1
`

func (q *Queries) TechCardItemDeleteByCard(ctx context.Context, techCardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, techCardItemDeleteByCard, techCardID)
	return err
}

const techCardItemInsert = `-- name: TechCardItemInsert :one
INSERT INTO tech_card_items (tech_card_id, ingredient_id, gross_qty, net_qty, unit)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tech_card_id, ingredient_id) DO UPDATE
    SET gross_qty = EXCLUDED.gross_qty,
        net_qty = EXCLUDED.net_qty,
        unit = EXCLUDED.unit,
        updated_at = now()
RETURNING id, tech_card_id, ingredient_id, gross_qty, net_qty, unit, created_at, updated_at
`

type TechCardItemInsertParams struct {
	TechCardID   uuid.UUID `json:"tech_card_id"`
	IngredientID uuid.UUID `json:"ingredient_id"`
	GrossQty     float64   `json:"gross_qty"`
	NetQty       float64   `json:"net_qty"`
	Unit         string    `json:"unit"`
}

func (q *Queries) TechCardItemInsert(ctx context.Context, arg TechCardItemInsertParams) (TechCardItem, error) {
	row := q.db.QueryRow(ctx, techCardItemInsert,
		arg.TechCardID,
		arg.IngredientID,
		arg.GrossQty,
		arg.NetQty,
		arg.Unit,
	)
	var i TechCardItem
	err := row.Scan(
		&i.ID,
		&i.TechCardID,
		&i.IngredientID,
		&i.GrossQty,
		&i.NetQty,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const techCardItemListByCard = `-- name: TechCardItemListByCard :many
SELECT tci.id, tci.tech_card_id, tci.ingredient_id, tci.gross_qty, tci.net_qty, tci.unit, tci.created_at, tci.updated_at, i.name AS ingredient_name, i.is_dough
FROM tech_card_items tci
JOIN ingredients i ON i.id = tci.ingredient_id
WHERE tci.tech_card_id = $1
ORDER BY i.name
`

type TechCardItemListByCardRow struct {
	ID             uuid.UUID `json:"id"`
	TechCardID     uuid.UUID `json:"tech_card_id"`
	IngredientID   uuid.UUID `json:"ingredient_id"`
	GrossQty       float64   `json:"gross_qty"`
	NetQty         float64   `json:"net_qty"`
	Unit           string    `json:"unit"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	IngredientName string    `json:"ingredient_name"`
	IsDough        bool      `json:"is_dough"`
}

func (q *Queries) TechCardItemListByCard(ctx context.Context, techCardID uuid.UUID) ([]TechCardItemListByCardRow, error) {
	rows, err := q.db.Query(ctx, techCardItemListByCard, techCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TechCardItemListByCardRow{}
	for rows.Next() {
		var i TechCardItemListByCardRow
		if err := rows.Scan(
			&i.ID,
			&i.TechCardID,
			&i.IngredientID,
			&i.GrossQty,
			&i.NetQty,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IngredientName,
			&i.IsDough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const techCardItemListDoughByCard = `-- name: TechCardItemListDoughByCard :many
SELECT tci.id, tci.tech_card_id, tci.ingredient_id, tci.gross_qty, tci.net_qty, tci.unit, tci.created_at, tci.updated_at, i.name AS ingredient_name
FROM tech_card_items tci
JOIN ingredients i ON i.id = tci.ingredient_id
WHERE tci.tech_card_id = $1
  AND i.is_dough = true
  AND i.deleted_at IS NULL
ORDER BY i.name
`

type TechCardItemListDoughByCardRow struct {
	ID             uuid.UUID `json:"id"`
	TechCardID     uuid.UUID `json:"tech_card_id"`
	IngredientID   uuid.UUID `json:"ingredient_id"`
	GrossQty       float64   `json:"gross_qty"`
	NetQty         float64   `json:"net_qty"`
	Unit           string    `json:"unit"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	IngredientName string    `json:"ingredient_name"`
}

func (q *Queries) TechCardItemListDoughByCard(ctx context.Context, techCardID uuid.UUID) ([]TechCardItemListDoughByCardRow, error) {
	rows, err := q.db.Query(ctx, techCardItemListDoughByCard, techCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TechCardItemListDoughByCardRow{}
	for rows.Next() {
		var i TechCardItemListDoughByCardRow
		if err := rows.Scan(
			&i.ID,
			&i.TechCardID,
			&i.IngredientID,
			&i.GrossQty,
			&i.NetQty,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IngredientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const techCardListByProduct = `-- name: TechCardListByProduct :many
SELECT id, product_id, version, source, source_ref, yield_qty, yield_unit, valid_from, valid_to, created_at, updated_at, deleted_at FROM tech_cards
WHERE product_id = $1 AND deleted_at IS NULL
ORDER BY version DESC
`

func (q *Queries) TechCardListByProduct(ctx context.Context, productID uuid.UUID) ([]TechCard, error) {
	rows, err := q.db.Query(ctx, techCardListByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TechCard{}
	for rows.Next() {
		var i TechCard
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Version,
			&i.Source,
			&i.SourceRef,
			&i.YieldQty,
			&i.YieldUnit,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const techCardSoftDelete = `-- name: TechCardSoftDelete :exec
UPDATE tech_cards SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TechCardSoftDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, techCardSoftDelete, id)
	return err
}
