// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
)

const createPasswordAuthUser = `-- name: CreatePasswordAuthUser :one
INSERT INTO auth_users (
    username,
    password_hash,
    metadata_json,
    role,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT(username) WHERE username <> '' DO UPDATE SET
    password_hash = excluded.password_hash,
    metadata_json = excluded.metadata_json,
    role = excluded.role,
    updated_at = excluded.updated_at
RETURNING id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at
`

type CreatePasswordAuthUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	MetadataJson string `json:"metadata_json"`
	Role         string `json:"role"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) CreatePasswordAuthUser(ctx context.Context, arg CreatePasswordAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createPasswordAuthUser,
		arg.Username,
		arg.PasswordHash,
		arg.MetadataJson,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByTelegramID = `-- name: GetAuthUserByTelegramID :one
SELECT id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at
FROM auth_users
WHERE telegram_id = $1
`

func (q *Queries) GetAuthUserByTelegramID(ctx context.Context, telegramID *int64) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByTelegramID, telegramID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByUsername = `-- name: GetAuthUserByUsername :one
SELECT id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at
FROM auth_users
WHERE username = $1
`

func (q *Queries) GetAuthUserByUsername(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByUsername, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkTelegramAuthUser = `-- name: LinkTelegramAuthUser :one
UPDATE auth_users
SET
    telegram_id = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at
`

type LinkTelegramAuthUserParams struct {
	TelegramID *int64 `json:"telegram_id"`
	UpdatedAt  string `json:"updated_at"`
	ID         int64  `json:"id"`
}

func (q *Queries) LinkTelegramAuthUser(ctx context.Context, arg LinkTelegramAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, linkTelegramAuthUser, arg.TelegramID, arg.UpdatedAt, arg.ID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlinkTelegramAuthUser = `-- name: UnlinkTelegramAuthUser :exec
UPDATE auth_users
SET
    telegram_id = NULL,
    updated_at = $1
WHERE telegram_id = $2
`

type UnlinkTelegramAuthUserParams struct {
	UpdatedAt  string `json:"updated_at"`
	TelegramID *int64 `json:"telegram_id"`
}

func (q *Queries) UnlinkTelegramAuthUser(ctx context.Context, arg UnlinkTelegramAuthUserParams) error {
	_, err := q.db.Exec(ctx, unlinkTelegramAuthUser, arg.UpdatedAt, arg.TelegramID)
	return err
}
