// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindTelegramID = `-- name: BindTelegramID :one
UPDATE auth_users
SET telegram_id = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
`

type BindTelegramIDParams struct {
	TelegramID *int64             `json:"telegram_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ID         int64              `json:"id"`
}

func (q *Queries) BindTelegramID(ctx context.Context, arg BindTelegramIDParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, bindTelegramID, arg.TelegramID, arg.UpdatedAt, arg.ID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentID,
		&i.TelegramUsername,
	)
	return i, err
}

const createPasswordAuthUser = `-- name: CreatePasswordAuthUser :one
INSERT INTO auth_users (
    department_id,
    username,
    telegram_username,
    password_hash,
    metadata_json,
    role,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT(username) WHERE username <> '' DO UPDATE SET
    department_id = excluded.department_id,
    telegram_username = excluded.telegram_username,
    password_hash = excluded.password_hash,
    metadata_json = excluded.metadata_json,
    role = excluded.role,
    updated_at = excluded.updated_at
RETURNING id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
`

type CreatePasswordAuthUserParams struct {
	DepartmentID     *int64             `json:"department_id"`
	Username         string             `json:"username"`
	TelegramUsername *string            `json:"telegram_username"`
	PasswordHash     string             `json:"password_hash"`
	MetadataJson     string             `json:"metadata_json"`
	Role             string             `json:"role"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePasswordAuthUser(ctx context.Context, arg CreatePasswordAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createPasswordAuthUser,
		arg.DepartmentID,
		arg.Username,
		arg.TelegramUsername,
		arg.PasswordHash,
		arg.MetadataJson,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentID,
		&i.TelegramUsername,
	)
	return i, err
}

const deleteAuthUser = `-- name: DeleteAuthUser :exec
DELETE FROM auth_users WHERE id = $1
`

func (q *Queries) DeleteAuthUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthUser, id)
	return err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
FROM auth_users
WHERE id = $1
`

func (q *Queries) GetAuthUserByID(ctx context.Context, id int64) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentID,
		&i.TelegramUsername,
	)
	return i, err
}

const getAuthUserByTelegramID = `-- name: GetAuthUserByTelegramID :one
SELECT id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
FROM auth_users
WHERE telegram_id = $1
`

func (q *Queries) GetAuthUserByTelegramID(ctx context.Context, telegramID *int64) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByTelegramID, telegramID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentID,
		&i.TelegramUsername,
	)
	return i, err
}

const getAuthUserByTelegramUsername = `-- name: GetAuthUserByTelegramUsername :one
SELECT id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
FROM auth_users
WHERE telegram_username = $1::text
  AND telegram_id IS NOT NULL
ORDER BY id
LIMIT 1
`

func (q *Queries) GetAuthUserByTelegramUsername(ctx context.Context, telegramUsername string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByTelegramUsername, telegramUsername)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentID,
		&i.TelegramUsername,
	)
	return i, err
}

const getAuthUserByUsername = `-- name: GetAuthUserByUsername :one
SELECT id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
FROM auth_users
WHERE username = $1
`

func (q *Queries) GetAuthUserByUsername(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByUsername, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentID,
		&i.TelegramUsername,
	)
	return i, err
}

const listAuthUsers = `-- name: ListAuthUsers :many
SELECT id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
FROM auth_users
ORDER BY id
`

func (q *Queries) ListAuthUsers(ctx context.Context) ([]AuthUser, error) {
	rows, err := q.db.Query(ctx, listAuthUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.PasswordHash,
			&i.MetadataJson,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartmentID,
			&i.TelegramUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthUsersByDepartmentID = `-- name: ListAuthUsersByDepartmentID :many
SELECT id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
FROM auth_users
WHERE department_id = $1
  AND telegram_id IS NOT NULL
ORDER BY id
`

func (q *Queries) ListAuthUsersByDepartmentID(ctx context.Context, departmentID *int64) ([]AuthUser, error) {
	rows, err := q.db.Query(ctx, listAuthUsersByDepartmentID, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.PasswordHash,
			&i.MetadataJson,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartmentID,
			&i.TelegramUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthUsersByRole = `-- name: ListAuthUsersByRole :many
SELECT id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
FROM auth_users
WHERE role = $1
  AND telegram_id IS NOT NULL
ORDER BY id
`

func (q *Queries) ListAuthUsersByRole(ctx context.Context, role string) ([]AuthUser, error) {
	rows, err := q.db.Query(ctx, listAuthUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.PasswordHash,
			&i.MetadataJson,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartmentID,
			&i.TelegramUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthUserPassword = `-- name: UpdateAuthUserPassword :one
UPDATE auth_users
SET password_hash = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
`

type UpdateAuthUserPasswordParams struct {
	PasswordHash string             `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ID           int64              `json:"id"`
}

func (q *Queries) UpdateAuthUserPassword(ctx context.Context, arg UpdateAuthUserPasswordParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateAuthUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentID,
		&i.TelegramUsername,
	)
	return i, err
}

const updateAuthUserRole = `-- name: UpdateAuthUserRole :one
UPDATE auth_users
SET role = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
`

type UpdateAuthUserRoleParams struct {
	Role      string             `json:"role"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        int64              `json:"id"`
}

func (q *Queries) UpdateAuthUserRole(ctx context.Context, arg UpdateAuthUserRoleParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateAuthUserRole, arg.Role, arg.UpdatedAt, arg.ID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentID,
		&i.TelegramUsername,
	)
	return i, err
}
