// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserDepartment = `-- name: AssignUserDepartment :one
UPDATE auth_users
SET
    department_id = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, telegram_id, username, password_hash, metadata_json, role, created_at, updated_at, department_id, telegram_username
`

type AssignUserDepartmentParams struct {
	DepartmentID *int64             `json:"department_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UserID       int64              `json:"user_id"`
}

func (q *Queries) AssignUserDepartment(ctx context.Context, arg AssignUserDepartmentParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, assignUserDepartment, arg.DepartmentID, arg.UpdatedAt, arg.UserID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.PasswordHash,
		&i.MetadataJson,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentID,
		&i.TelegramUsername,
	)
	return i, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
    type,
    code,
    name,
    iiko_department_id,
    metadata_json,
    is_active,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, type, code, name, iiko_department_id, metadata_json, is_active, created_at, updated_at
`

type CreateDepartmentParams struct {
	Type             string             `json:"type"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	IikoDepartmentID *string            `json:"iiko_department_id"`
	MetadataJson     string             `json:"metadata_json"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.Type,
		arg.Code,
		arg.Name,
		arg.IikoDepartmentID,
		arg.MetadataJson,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.IikoDepartmentID,
		&i.MetadataJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByCode = `-- name: GetDepartmentByCode :one
SELECT id, type, code, name, iiko_department_id, metadata_json, is_active, created_at, updated_at
FROM departments
WHERE code = $1
`

func (q *Queries) GetDepartmentByCode(ctx context.Context, code string) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByCode, code)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.IikoDepartmentID,
		&i.MetadataJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, type, code, name, iiko_department_id, metadata_json, is_active, created_at, updated_at
FROM departments
WHERE id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id int64) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.IikoDepartmentID,
		&i.MetadataJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, type, code, name, iiko_department_id, metadata_json, is_active, created_at, updated_at
FROM departments
WHERE type = COALESCE($1, type)
ORDER BY type, name, id
`

func (q *Queries) ListDepartments(ctx context.Context, type_ *string) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Code,
			&i.Name,
			&i.IikoDepartmentID,
			&i.MetadataJson,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
