// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: iiko_snapshot.sql

package sqlc

import (
	"context"
)

const createIikoSyncRun = `-- name: CreateIikoSyncRun :one
INSERT INTO iiko_sync_runs (
    source,
    date_from,
    date_to,
    known_revision,
    status,
    error,
    started_at,
    finished_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, source, date_from, date_to, known_revision, status, error, started_at, finished_at
`

type CreateIikoSyncRunParams struct {
	Source        string  `json:"source"`
	DateFrom      string  `json:"date_from"`
	DateTo        string  `json:"date_to"`
	KnownRevision int64   `json:"known_revision"`
	Status        string  `json:"status"`
	Error         string  `json:"error"`
	StartedAt     string  `json:"started_at"`
	FinishedAt    *string `json:"finished_at"`
}

func (q *Queries) CreateIikoSyncRun(ctx context.Context, arg CreateIikoSyncRunParams) (IikoSyncRun, error) {
	row := q.db.QueryRow(ctx, createIikoSyncRun,
		arg.Source,
		arg.DateFrom,
		arg.DateTo,
		arg.KnownRevision,
		arg.Status,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i IikoSyncRun
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.DateFrom,
		&i.DateTo,
		&i.KnownRevision,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteIikoAssemblyChartItemsByChartID = `-- name: DeleteIikoAssemblyChartItemsByChartID :exec
DELETE FROM iiko_assembly_chart_items
WHERE chart_id = $1
`

func (q *Queries) DeleteIikoAssemblyChartItemsByChartID(ctx context.Context, chartID string) error {
	_, err := q.db.Exec(ctx, deleteIikoAssemblyChartItemsByChartID, chartID)
	return err
}

const deleteIikoPreparedChartItemsByChartID = `-- name: DeleteIikoPreparedChartItemsByChartID :exec
DELETE FROM iiko_prepared_chart_items
WHERE prepared_chart_id = $1
`

func (q *Queries) DeleteIikoPreparedChartItemsByChartID(ctx context.Context, preparedChartID string) error {
	_, err := q.db.Exec(ctx, deleteIikoPreparedChartItemsByChartID, preparedChartID)
	return err
}

const finishIikoSyncRun = `-- name: FinishIikoSyncRun :one
UPDATE iiko_sync_runs
SET
    known_revision = $1,
    status = $2,
    error = $3,
    finished_at = $4
WHERE id = $5
RETURNING id, source, date_from, date_to, known_revision, status, error, started_at, finished_at
`

type FinishIikoSyncRunParams struct {
	KnownRevision int64   `json:"known_revision"`
	Status        string  `json:"status"`
	Error         string  `json:"error"`
	FinishedAt    *string `json:"finished_at"`
	ID            int64   `json:"id"`
}

func (q *Queries) FinishIikoSyncRun(ctx context.Context, arg FinishIikoSyncRunParams) (IikoSyncRun, error) {
	row := q.db.QueryRow(ctx, finishIikoSyncRun,
		arg.KnownRevision,
		arg.Status,
		arg.Error,
		arg.FinishedAt,
		arg.ID,
	)
	var i IikoSyncRun
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.DateFrom,
		&i.DateTo,
		&i.KnownRevision,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertIikoAssemblyChartItem = `-- name: InsertIikoAssemblyChartItem :one
INSERT INTO iiko_assembly_chart_items (
    id,
    chart_id,
    sort_weight,
    product_id,
    product_size_spec_json,
    store_spec_json,
    amount_in,
    amount_middle,
    amount_out,
    amount_in1,
    amount_out1,
    amount_in2,
    amount_out2,
    amount_in3,
    amount_out3,
    package_count,
    package_type_id,
    raw_json
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
RETURNING id, chart_id, sort_weight, product_id, product_size_spec_json, store_spec_json, amount_in, amount_middle, amount_out, amount_in1, amount_out1, amount_in2, amount_out2, amount_in3, amount_out3, package_count, package_type_id, raw_json
`

type InsertIikoAssemblyChartItemParams struct {
	ID                  string  `json:"id"`
	ChartID             string  `json:"chart_id"`
	SortWeight          float64 `json:"sort_weight"`
	ProductID           string  `json:"product_id"`
	ProductSizeSpecJson string  `json:"product_size_spec_json"`
	StoreSpecJson       string  `json:"store_spec_json"`
	AmountIn            float64 `json:"amount_in"`
	AmountMiddle        float64 `json:"amount_middle"`
	AmountOut           float64 `json:"amount_out"`
	AmountIn1           float64 `json:"amount_in1"`
	AmountOut1          float64 `json:"amount_out1"`
	AmountIn2           float64 `json:"amount_in2"`
	AmountOut2          float64 `json:"amount_out2"`
	AmountIn3           float64 `json:"amount_in3"`
	AmountOut3          float64 `json:"amount_out3"`
	PackageCount        float64 `json:"package_count"`
	PackageTypeID       *string `json:"package_type_id"`
	RawJson             string  `json:"raw_json"`
}

func (q *Queries) InsertIikoAssemblyChartItem(ctx context.Context, arg InsertIikoAssemblyChartItemParams) (IikoAssemblyChartItem, error) {
	row := q.db.QueryRow(ctx, insertIikoAssemblyChartItem,
		arg.ID,
		arg.ChartID,
		arg.SortWeight,
		arg.ProductID,
		arg.ProductSizeSpecJson,
		arg.StoreSpecJson,
		arg.AmountIn,
		arg.AmountMiddle,
		arg.AmountOut,
		arg.AmountIn1,
		arg.AmountOut1,
		arg.AmountIn2,
		arg.AmountOut2,
		arg.AmountIn3,
		arg.AmountOut3,
		arg.PackageCount,
		arg.PackageTypeID,
		arg.RawJson,
	)
	var i IikoAssemblyChartItem
	err := row.Scan(
		&i.ID,
		&i.ChartID,
		&i.SortWeight,
		&i.ProductID,
		&i.ProductSizeSpecJson,
		&i.StoreSpecJson,
		&i.AmountIn,
		&i.AmountMiddle,
		&i.AmountOut,
		&i.AmountIn1,
		&i.AmountOut1,
		&i.AmountIn2,
		&i.AmountOut2,
		&i.AmountIn3,
		&i.AmountOut3,
		&i.PackageCount,
		&i.PackageTypeID,
		&i.RawJson,
	)
	return i, err
}

const insertIikoPreparedChartItem = `-- name: InsertIikoPreparedChartItem :one
INSERT INTO iiko_prepared_chart_items (
    id,
    prepared_chart_id,
    sort_weight,
    product_id,
    product_size_spec_json,
    store_spec_json,
    amount,
    raw_json
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, prepared_chart_id, sort_weight, product_id, product_size_spec_json, store_spec_json, amount, raw_json
`

type InsertIikoPreparedChartItemParams struct {
	ID                  string  `json:"id"`
	PreparedChartID     string  `json:"prepared_chart_id"`
	SortWeight          float64 `json:"sort_weight"`
	ProductID           string  `json:"product_id"`
	ProductSizeSpecJson string  `json:"product_size_spec_json"`
	StoreSpecJson       string  `json:"store_spec_json"`
	Amount              float64 `json:"amount"`
	RawJson             string  `json:"raw_json"`
}

func (q *Queries) InsertIikoPreparedChartItem(ctx context.Context, arg InsertIikoPreparedChartItemParams) (IikoPreparedChartItem, error) {
	row := q.db.QueryRow(ctx, insertIikoPreparedChartItem,
		arg.ID,
		arg.PreparedChartID,
		arg.SortWeight,
		arg.ProductID,
		arg.ProductSizeSpecJson,
		arg.StoreSpecJson,
		arg.Amount,
		arg.RawJson,
	)
	var i IikoPreparedChartItem
	err := row.Scan(
		&i.ID,
		&i.PreparedChartID,
		&i.SortWeight,
		&i.ProductID,
		&i.ProductSizeSpecJson,
		&i.StoreSpecJson,
		&i.Amount,
		&i.RawJson,
	)
	return i, err
}

const upsertIikoAssemblyChart = `-- name: UpsertIikoAssemblyChart :one
INSERT INTO iiko_assembly_charts (
    id,
    assembled_product_id,
    date_from,
    date_to,
    assembled_amount,
    product_writeoff_strategy,
    product_size_assembly_strategy,
    effective_direct_writeoff_store_spec_json,
    raw_json,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT(id) DO UPDATE SET
    assembled_product_id = excluded.assembled_product_id,
    date_from = excluded.date_from,
    date_to = excluded.date_to,
    assembled_amount = excluded.assembled_amount,
    product_writeoff_strategy = excluded.product_writeoff_strategy,
    product_size_assembly_strategy = excluded.product_size_assembly_strategy,
    effective_direct_writeoff_store_spec_json = excluded.effective_direct_writeoff_store_spec_json,
    raw_json = excluded.raw_json,
    updated_at = excluded.updated_at
RETURNING id, assembled_product_id, date_from, date_to, assembled_amount, product_writeoff_strategy, product_size_assembly_strategy, effective_direct_writeoff_store_spec_json, raw_json, updated_at
`

type UpsertIikoAssemblyChartParams struct {
	ID                                   string  `json:"id"`
	AssembledProductID                   string  `json:"assembled_product_id"`
	DateFrom                             string  `json:"date_from"`
	DateTo                               *string `json:"date_to"`
	AssembledAmount                      float64 `json:"assembled_amount"`
	ProductWriteoffStrategy              string  `json:"product_writeoff_strategy"`
	ProductSizeAssemblyStrategy          string  `json:"product_size_assembly_strategy"`
	EffectiveDirectWriteoffStoreSpecJson string  `json:"effective_direct_writeoff_store_spec_json"`
	RawJson                              string  `json:"raw_json"`
	UpdatedAt                            string  `json:"updated_at"`
}

func (q *Queries) UpsertIikoAssemblyChart(ctx context.Context, arg UpsertIikoAssemblyChartParams) (IikoAssemblyChart, error) {
	row := q.db.QueryRow(ctx, upsertIikoAssemblyChart,
		arg.ID,
		arg.AssembledProductID,
		arg.DateFrom,
		arg.DateTo,
		arg.AssembledAmount,
		arg.ProductWriteoffStrategy,
		arg.ProductSizeAssemblyStrategy,
		arg.EffectiveDirectWriteoffStoreSpecJson,
		arg.RawJson,
		arg.UpdatedAt,
	)
	var i IikoAssemblyChart
	err := row.Scan(
		&i.ID,
		&i.AssembledProductID,
		&i.DateFrom,
		&i.DateTo,
		&i.AssembledAmount,
		&i.ProductWriteoffStrategy,
		&i.ProductSizeAssemblyStrategy,
		&i.EffectiveDirectWriteoffStoreSpecJson,
		&i.RawJson,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIikoPreparedChart = `-- name: UpsertIikoPreparedChart :one
INSERT INTO iiko_prepared_charts (
    id,
    assembled_product_id,
    date_from,
    date_to,
    product_size_assembly_strategy,
    effective_direct_writeoff_store_spec_json,
    raw_json,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT(id) DO UPDATE SET
    assembled_product_id = excluded.assembled_product_id,
    date_from = excluded.date_from,
    date_to = excluded.date_to,
    product_size_assembly_strategy = excluded.product_size_assembly_strategy,
    effective_direct_writeoff_store_spec_json = excluded.effective_direct_writeoff_store_spec_json,
    raw_json = excluded.raw_json,
    updated_at = excluded.updated_at
RETURNING id, assembled_product_id, date_from, date_to, product_size_assembly_strategy, effective_direct_writeoff_store_spec_json, raw_json, updated_at
`

type UpsertIikoPreparedChartParams struct {
	ID                                   string  `json:"id"`
	AssembledProductID                   string  `json:"assembled_product_id"`
	DateFrom                             string  `json:"date_from"`
	DateTo                               *string `json:"date_to"`
	ProductSizeAssemblyStrategy          string  `json:"product_size_assembly_strategy"`
	EffectiveDirectWriteoffStoreSpecJson string  `json:"effective_direct_writeoff_store_spec_json"`
	RawJson                              string  `json:"raw_json"`
	UpdatedAt                            string  `json:"updated_at"`
}

func (q *Queries) UpsertIikoPreparedChart(ctx context.Context, arg UpsertIikoPreparedChartParams) (IikoPreparedChart, error) {
	row := q.db.QueryRow(ctx, upsertIikoPreparedChart,
		arg.ID,
		arg.AssembledProductID,
		arg.DateFrom,
		arg.DateTo,
		arg.ProductSizeAssemblyStrategy,
		arg.EffectiveDirectWriteoffStoreSpecJson,
		arg.RawJson,
		arg.UpdatedAt,
	)
	var i IikoPreparedChart
	err := row.Scan(
		&i.ID,
		&i.AssembledProductID,
		&i.DateFrom,
		&i.DateTo,
		&i.ProductSizeAssemblyStrategy,
		&i.EffectiveDirectWriteoffStoreSpecJson,
		&i.RawJson,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIikoProduct = `-- name: UpsertIikoProduct :one
INSERT INTO iiko_products (
    id,
    code,
    name,
    type,
    measure_unit,
    raw_json,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT(id) DO UPDATE SET
    code = excluded.code,
    name = excluded.name,
    type = excluded.type,
    measure_unit = excluded.measure_unit,
    raw_json = excluded.raw_json,
    updated_at = excluded.updated_at
RETURNING id, code, name, type, measure_unit, raw_json, updated_at
`

type UpsertIikoProductParams struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
	UpdatedAt   string  `json:"updated_at"`
}

func (q *Queries) UpsertIikoProduct(ctx context.Context, arg UpsertIikoProductParams) (IikoProduct, error) {
	row := q.db.QueryRow(ctx, upsertIikoProduct,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.MeasureUnit,
		arg.RawJson,
		arg.UpdatedAt,
	)
	var i IikoProduct
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.MeasureUnit,
		&i.RawJson,
		&i.UpdatedAt,
	)
	return i, err
}
