// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type AuthUser struct {
	ID           int64  `json:"id"`
	TelegramID   *int64 `json:"telegram_id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	MetadataJson string `json:"metadata_json"`
	Role         string `json:"role"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type IikoAssemblyChart struct {
	ID                                   string  `json:"id"`
	AssembledProductID                   string  `json:"assembled_product_id"`
	DateFrom                             string  `json:"date_from"`
	DateTo                               *string `json:"date_to"`
	AssembledAmount                      float64 `json:"assembled_amount"`
	ProductWriteoffStrategy              string  `json:"product_writeoff_strategy"`
	ProductSizeAssemblyStrategy          string  `json:"product_size_assembly_strategy"`
	EffectiveDirectWriteoffStoreSpecJson string  `json:"effective_direct_writeoff_store_spec_json"`
	RawJson                              string  `json:"raw_json"`
	UpdatedAt                            string  `json:"updated_at"`
}

type IikoAssemblyChartItem struct {
	ID                  string  `json:"id"`
	ChartID             string  `json:"chart_id"`
	SortWeight          float64 `json:"sort_weight"`
	ProductID           string  `json:"product_id"`
	ProductSizeSpecJson string  `json:"product_size_spec_json"`
	StoreSpecJson       string  `json:"store_spec_json"`
	AmountIn            float64 `json:"amount_in"`
	AmountMiddle        float64 `json:"amount_middle"`
	AmountOut           float64 `json:"amount_out"`
	AmountIn1           float64 `json:"amount_in1"`
	AmountOut1          float64 `json:"amount_out1"`
	AmountIn2           float64 `json:"amount_in2"`
	AmountOut2          float64 `json:"amount_out2"`
	AmountIn3           float64 `json:"amount_in3"`
	AmountOut3          float64 `json:"amount_out3"`
	PackageCount        float64 `json:"package_count"`
	PackageTypeID       *string `json:"package_type_id"`
	RawJson             string  `json:"raw_json"`
}

type IikoPreparedChart struct {
	ID                                   string  `json:"id"`
	AssembledProductID                   string  `json:"assembled_product_id"`
	DateFrom                             string  `json:"date_from"`
	DateTo                               *string `json:"date_to"`
	ProductSizeAssemblyStrategy          string  `json:"product_size_assembly_strategy"`
	EffectiveDirectWriteoffStoreSpecJson string  `json:"effective_direct_writeoff_store_spec_json"`
	RawJson                              string  `json:"raw_json"`
	UpdatedAt                            string  `json:"updated_at"`
}

type IikoPreparedChartItem struct {
	ID                  string  `json:"id"`
	PreparedChartID     string  `json:"prepared_chart_id"`
	SortWeight          float64 `json:"sort_weight"`
	ProductID           string  `json:"product_id"`
	ProductSizeSpecJson string  `json:"product_size_spec_json"`
	StoreSpecJson       string  `json:"store_spec_json"`
	Amount              float64 `json:"amount"`
	RawJson             string  `json:"raw_json"`
}

type IikoProduct struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
	UpdatedAt   string  `json:"updated_at"`
}

type IikoSyncRun struct {
	ID            int64   `json:"id"`
	Source        string  `json:"source"`
	DateFrom      string  `json:"date_from"`
	DateTo        string  `json:"date_to"`
	KnownRevision int64   `json:"known_revision"`
	Status        string  `json:"status"`
	Error         string  `json:"error"`
	StartedAt     string  `json:"started_at"`
	FinishedAt    *string `json:"finished_at"`
}

type Order struct {
	ID        int64  `json:"id"`
	Number    string `json:"number"`
	Location  string `json:"location"`
	CreatedAt string `json:"created_at"`
}

type OrderCounter struct {
	Day     string `json:"day"`
	Counter int64  `json:"counter"`
}

type OrderItem struct {
	ID            int64   `json:"id"`
	OrderID       int64   `json:"order_id"`
	IikoProductID *string `json:"iiko_product_id"`
	ProductName   string  `json:"product_name"`
	Quantity      float64 `json:"quantity"`
}
