// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID               int64              `json:"id"`
	TelegramID       *int64             `json:"telegram_id"`
	Username         string             `json:"username"`
	PasswordHash     string             `json:"password_hash"`
	MetadataJson     string             `json:"metadata_json"`
	Role             string             `json:"role"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DepartmentID     *int64             `json:"department_id"`
	TelegramUsername *string            `json:"telegram_username"`
}

type Department struct {
	ID               int64              `json:"id"`
	Type             string             `json:"type"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	IikoDepartmentID *string            `json:"iiko_department_id"`
	MetadataJson     string             `json:"metadata_json"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type DishCatalog struct {
	ID         int64              `json:"id"`
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	SortOrder  int64              `json:"sort_order"`
	CategoryID *int64             `json:"category_id"`
	GroupID    *int64             `json:"group_id"`
}

type DishGroup struct {
	ID         int64              `json:"id"`
	CategoryID *int64             `json:"category_id"`
	Name       string             `json:"name"`
	SortOrder  int64              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type IikoAssemblyChart struct {
	ID                                   string             `json:"id"`
	AssembledProductID                   string             `json:"assembled_product_id"`
	DateFrom                             string             `json:"date_from"`
	DateTo                               *string            `json:"date_to"`
	AssembledAmount                      float64            `json:"assembled_amount"`
	ProductWriteoffStrategy              string             `json:"product_writeoff_strategy"`
	ProductSizeAssemblyStrategy          string             `json:"product_size_assembly_strategy"`
	EffectiveDirectWriteoffStoreSpecJson string             `json:"effective_direct_writeoff_store_spec_json"`
	RawJson                              string             `json:"raw_json"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
}

type IikoAssemblyChartItem struct {
	ID                  string  `json:"id"`
	ChartID             string  `json:"chart_id"`
	SortWeight          float64 `json:"sort_weight"`
	ProductID           string  `json:"product_id"`
	ProductSizeSpecJson string  `json:"product_size_spec_json"`
	StoreSpecJson       string  `json:"store_spec_json"`
	AmountIn            float64 `json:"amount_in"`
	AmountMiddle        float64 `json:"amount_middle"`
	AmountOut           float64 `json:"amount_out"`
	AmountIn1           float64 `json:"amount_in1"`
	AmountOut1          float64 `json:"amount_out1"`
	AmountIn2           float64 `json:"amount_in2"`
	AmountOut2          float64 `json:"amount_out2"`
	AmountIn3           float64 `json:"amount_in3"`
	AmountOut3          float64 `json:"amount_out3"`
	PackageCount        float64 `json:"package_count"`
	PackageTypeID       *string `json:"package_type_id"`
	RawJson             string  `json:"raw_json"`
}

type IikoPreparedChart struct {
	ID                                   string             `json:"id"`
	AssembledProductID                   string             `json:"assembled_product_id"`
	DateFrom                             string             `json:"date_from"`
	DateTo                               *string            `json:"date_to"`
	ProductSizeAssemblyStrategy          string             `json:"product_size_assembly_strategy"`
	EffectiveDirectWriteoffStoreSpecJson string             `json:"effective_direct_writeoff_store_spec_json"`
	RawJson                              string             `json:"raw_json"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
}

type IikoPreparedChartItem struct {
	ID                  string  `json:"id"`
	PreparedChartID     string  `json:"prepared_chart_id"`
	SortWeight          float64 `json:"sort_weight"`
	ProductID           string  `json:"product_id"`
	ProductSizeSpecJson string  `json:"product_size_spec_json"`
	StoreSpecJson       string  `json:"store_spec_json"`
	Amount              float64 `json:"amount"`
	RawJson             string  `json:"raw_json"`
}

type IikoProduct struct {
	ID          string             `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Type        *string            `json:"type"`
	MeasureUnit string             `json:"measure_unit"`
	RawJson     string             `json:"raw_json"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IikoSyncRun struct {
	ID            int64              `json:"id"`
	Source        string             `json:"source"`
	DateFrom      string             `json:"date_from"`
	DateTo        string             `json:"date_to"`
	KnownRevision int64              `json:"known_revision"`
	Status        string             `json:"status"`
	Error         string             `json:"error"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type Order struct {
	ID                  int64              `json:"id"`
	Number              string             `json:"number"`
	Location            string             `json:"location"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	FromDepartmentID    *int64             `json:"from_department_id"`
	ToDepartmentID      *int64             `json:"to_department_id"`
	FulfillmentDate     pgtype.Date        `json:"fulfillment_date"`
	CreatedByUsername   string             `json:"created_by_username"`
	Comments            []byte             `json:"comments"`
	IsFavorite          bool               `json:"is_favorite"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	CancelledByUsername string             `json:"cancelled_by_username"`
	CategoryID          *int64             `json:"category_id"`
	DedupKey            *string            `json:"dedup_key"`
}

type OrderCategory struct {
	ID           int64              `json:"id"`
	Code         string             `json:"code"`
	Letter       string             `json:"letter"`
	Name         string             `json:"name"`
	Color        string             `json:"color"`
	SortOrder    int64              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	MonitorCodes []string           `json:"monitor_codes"`
}

type OrderCounter struct {
	Day          string `json:"day"`
	Counter      int64  `json:"counter"`
	DepartmentID int64  `json:"department_id"`
	CategoryID   int64  `json:"category_id"`
}

type OrderDraft struct {
	ID                int64              `json:"id"`
	CreatedByUsername string             `json:"created_by_username"`
	CategoryID        int64              `json:"category_id"`
	FromDepartmentID  *int64             `json:"from_department_id"`
	FulfillmentDate   pgtype.Date        `json:"fulfillment_date"`
	Comments          []byte             `json:"comments"`
	Items             []byte             `json:"items"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type OrderHistory struct {
	ID                int64              `json:"id"`
	OrderID           int64              `json:"order_id"`
	ChangedByUsername string             `json:"changed_by_username"`
	ChangedAt         pgtype.Timestamptz `json:"changed_at"`
}

type OrderHistoryItem struct {
	ID                  int64    `json:"id"`
	HistoryID           int64    `json:"history_id"`
	ChangeType          string   `json:"change_type"`
	ProductCode         string   `json:"product_code"`
	ProductName         string   `json:"product_name"`
	OldQuantity         *float64 `json:"old_quantity"`
	NewQuantity         *float64 `json:"new_quantity"`
	OldReservedQuantity *float64 `json:"old_reserved_quantity"`
	NewReservedQuantity *float64 `json:"new_reserved_quantity"`
}

type OrderItem struct {
	ID               int64   `json:"id"`
	OrderID          int64   `json:"order_id"`
	IikoProductID    *string `json:"iiko_product_id"`
	ProductName      string  `json:"product_name"`
	Quantity         float64 `json:"quantity"`
	ReservedQuantity float64 `json:"reserved_quantity"`
}

type OrderOutbox struct {
	ID            int64              `json:"id"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	CorrelationID string             `json:"correlation_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

type ProductionSheet struct {
	ID                int64              `json:"id"`
	CreatedByUsername string             `json:"created_by_username"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProductionSheetItem struct {
	ID               int64   `json:"id"`
	SheetID          int64   `json:"sheet_id"`
	OrderID          int64   `json:"order_id"`
	ProductName      string  `json:"product_name"`
	ProducedQuantity float64 `json:"produced_quantity"`
	Reason           string  `json:"reason"`
}

type ProductionSheetLoad struct {
	SheetID        int64   `json:"sheet_id"`
	OrderID        int64   `json:"order_id"`
	ProductName    string  `json:"product_name"`
	LoadedQuantity float64 `json:"loaded_quantity"`
}

type ProductionSheetOrder struct {
	SheetID int64 `json:"sheet_id"`
	OrderID int64 `json:"order_id"`
}
