// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveAssemblyChartByProductID = `-- name: GetActiveAssemblyChartByProductID :one
SELECT
    id,
    assembled_product_id,
    assembled_amount,
    date_from,
    date_to
FROM iiko_assembly_charts
WHERE assembled_product_id = $1
  AND date_from::date <= $2::date
  AND (date_to IS NULL OR date_to::date >= $2::date)
ORDER BY date_from::date DESC
LIMIT 1
`

type GetActiveAssemblyChartByProductIDParams struct {
	AssembledProductID string      `json:"assembled_product_id"`
	OrderDate          pgtype.Date `json:"order_date"`
}

type GetActiveAssemblyChartByProductIDRow struct {
	ID                 string  `json:"id"`
	AssembledProductID string  `json:"assembled_product_id"`
	AssembledAmount    float64 `json:"assembled_amount"`
	DateFrom           string  `json:"date_from"`
	DateTo             *string `json:"date_to"`
}

func (q *Queries) GetActiveAssemblyChartByProductID(ctx context.Context, arg GetActiveAssemblyChartByProductIDParams) (GetActiveAssemblyChartByProductIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveAssemblyChartByProductID, arg.AssembledProductID, arg.OrderDate)
	var i GetActiveAssemblyChartByProductIDRow
	err := row.Scan(
		&i.ID,
		&i.AssembledProductID,
		&i.AssembledAmount,
		&i.DateFrom,
		&i.DateTo,
	)
	return i, err
}

const getActiveAssemblyChartFullByProductID = `-- name: GetActiveAssemblyChartFullByProductID :one
SELECT id, assembled_product_id, date_from, date_to, assembled_amount, product_writeoff_strategy, product_size_assembly_strategy, effective_direct_writeoff_store_spec_json, raw_json, updated_at
FROM iiko_assembly_charts
WHERE assembled_product_id = $1
  AND date_from::date <= $2::date
  AND (date_to IS NULL OR date_to::date >= $2::date)
ORDER BY date_from::date DESC
LIMIT 1
`

type GetActiveAssemblyChartFullByProductIDParams struct {
	AssembledProductID string      `json:"assembled_product_id"`
	OrderDate          pgtype.Date `json:"order_date"`
}

func (q *Queries) GetActiveAssemblyChartFullByProductID(ctx context.Context, arg GetActiveAssemblyChartFullByProductIDParams) (IikoAssemblyChart, error) {
	row := q.db.QueryRow(ctx, getActiveAssemblyChartFullByProductID, arg.AssembledProductID, arg.OrderDate)
	var i IikoAssemblyChart
	err := row.Scan(
		&i.ID,
		&i.AssembledProductID,
		&i.DateFrom,
		&i.DateTo,
		&i.AssembledAmount,
		&i.ProductWriteoffStrategy,
		&i.ProductSizeAssemblyStrategy,
		&i.EffectiveDirectWriteoffStoreSpecJson,
		&i.RawJson,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePreparedChartFullByProductID = `-- name: GetActivePreparedChartFullByProductID :one
SELECT id, assembled_product_id, date_from, date_to, product_size_assembly_strategy, effective_direct_writeoff_store_spec_json, raw_json, updated_at
FROM iiko_prepared_charts
WHERE assembled_product_id = $1
  AND date_from::date <= $2::date
  AND (date_to IS NULL OR date_to::date >= $2::date)
ORDER BY date_from::date DESC
LIMIT 1
`

type GetActivePreparedChartFullByProductIDParams struct {
	AssembledProductID string      `json:"assembled_product_id"`
	OrderDate          pgtype.Date `json:"order_date"`
}

func (q *Queries) GetActivePreparedChartFullByProductID(ctx context.Context, arg GetActivePreparedChartFullByProductIDParams) (IikoPreparedChart, error) {
	row := q.db.QueryRow(ctx, getActivePreparedChartFullByProductID, arg.AssembledProductID, arg.OrderDate)
	var i IikoPreparedChart
	err := row.Scan(
		&i.ID,
		&i.AssembledProductID,
		&i.DateFrom,
		&i.DateTo,
		&i.ProductSizeAssemblyStrategy,
		&i.EffectiveDirectWriteoffStoreSpecJson,
		&i.RawJson,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssemblyChartItemsByChartID = `-- name: ListAssemblyChartItemsByChartID :many
SELECT
    i.id AS item_id,
    i.product_id,
    i.amount_in,
    i.amount_out,
    COALESCE(p.name, '') AS product_name,
    COALESCE(p.code, '') AS product_code,
    COALESCE(p.measure_unit, '') AS measure_unit
FROM iiko_assembly_chart_items AS i
LEFT JOIN iiko_products AS p ON p.id = i.product_id
WHERE i.chart_id = $1
ORDER BY i.sort_weight, i.id
`

type ListAssemblyChartItemsByChartIDRow struct {
	ItemID      string  `json:"item_id"`
	ProductID   string  `json:"product_id"`
	AmountIn    float64 `json:"amount_in"`
	AmountOut   float64 `json:"amount_out"`
	ProductName string  `json:"product_name"`
	ProductCode string  `json:"product_code"`
	MeasureUnit string  `json:"measure_unit"`
}

func (q *Queries) ListAssemblyChartItemsByChartID(ctx context.Context, chartID string) ([]ListAssemblyChartItemsByChartIDRow, error) {
	rows, err := q.db.Query(ctx, listAssemblyChartItemsByChartID, chartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssemblyChartItemsByChartIDRow
	for rows.Next() {
		var i ListAssemblyChartItemsByChartIDRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ProductID,
			&i.AmountIn,
			&i.AmountOut,
			&i.ProductName,
			&i.ProductCode,
			&i.MeasureUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreparedChartItemsByChartID = `-- name: ListPreparedChartItemsByChartID :many
SELECT
    i.id AS item_id,
    i.product_id,
    i.amount,
    COALESCE(p.name, '') AS product_name,
    COALESCE(p.code, '') AS product_code,
    COALESCE(p.measure_unit, '') AS measure_unit
FROM iiko_prepared_chart_items AS i
LEFT JOIN iiko_products AS p ON p.id = i.product_id
WHERE i.prepared_chart_id = $1
ORDER BY i.sort_weight, i.id
`

type ListPreparedChartItemsByChartIDRow struct {
	ItemID      string  `json:"item_id"`
	ProductID   string  `json:"product_id"`
	Amount      float64 `json:"amount"`
	ProductName string  `json:"product_name"`
	ProductCode string  `json:"product_code"`
	MeasureUnit string  `json:"measure_unit"`
}

func (q *Queries) ListPreparedChartItemsByChartID(ctx context.Context, preparedChartID string) ([]ListPreparedChartItemsByChartIDRow, error) {
	rows, err := q.db.Query(ctx, listPreparedChartItemsByChartID, preparedChartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPreparedChartItemsByChartIDRow
	for rows.Next() {
		var i ListPreparedChartItemsByChartIDRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ProductID,
			&i.Amount,
			&i.ProductName,
			&i.ProductCode,
			&i.MeasureUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
