// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*)
FROM orders
WHERE
    ($1::BIGINT IS NULL OR from_department_id = $1::BIGINT)
    AND ($2::DATE IS NULL OR fulfillment_date = $2::DATE)
`

type CountOrdersParams struct {
	FromDepartmentID *int64      `json:"from_department_id"`
	FulfillmentDate  pgtype.Date `json:"fulfillment_date"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, arg.FromDepartmentID, arg.FulfillmentDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    number,
    location,
    from_department_id,
    to_department_id,
    created_at,
    fulfillment_date,
    created_by_username,
    comments
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, number, location, created_at, from_department_id, to_department_id, fulfillment_date, created_by_username, comments, is_favorite
`

type CreateOrderParams struct {
	Number            string             `json:"number"`
	Location          string             `json:"location"`
	FromDepartmentID  *int64             `json:"from_department_id"`
	ToDepartmentID    *int64             `json:"to_department_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	FulfillmentDate   pgtype.Date        `json:"fulfillment_date"`
	CreatedByUsername string             `json:"created_by_username"`
	Comments          []byte             `json:"comments"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Number,
		arg.Location,
		arg.FromDepartmentID,
		arg.ToDepartmentID,
		arg.CreatedAt,
		arg.FulfillmentDate,
		arg.CreatedByUsername,
		arg.Comments,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
		&i.FulfillmentDate,
		&i.CreatedByUsername,
		&i.Comments,
		&i.IsFavorite,
	)
	return i, err
}

const createOrderCounterDay = `-- name: CreateOrderCounterDay :exec
INSERT INTO order_counters(day, department_id, counter)
VALUES ($1, $2, 0)
ON CONFLICT(day, department_id) DO NOTHING
`

type CreateOrderCounterDayParams struct {
	Day          string `json:"day"`
	DepartmentID int64  `json:"department_id"`
}

func (q *Queries) CreateOrderCounterDay(ctx context.Context, arg CreateOrderCounterDayParams) error {
	_, err := q.db.Exec(ctx, createOrderCounterDay, arg.Day, arg.DepartmentID)
	return err
}

const createOrderHistory = `-- name: CreateOrderHistory :one
INSERT INTO order_history (
    order_id,
    changed_by_username,
    changed_at
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, order_id, changed_by_username, changed_at
`

type CreateOrderHistoryParams struct {
	OrderID           int64              `json:"order_id"`
	ChangedByUsername string             `json:"changed_by_username"`
	ChangedAt         pgtype.Timestamptz `json:"changed_at"`
}

func (q *Queries) CreateOrderHistory(ctx context.Context, arg CreateOrderHistoryParams) (OrderHistory, error) {
	row := q.db.QueryRow(ctx, createOrderHistory, arg.OrderID, arg.ChangedByUsername, arg.ChangedAt)
	var i OrderHistory
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ChangedByUsername,
		&i.ChangedAt,
	)
	return i, err
}

const createOrderHistoryItem = `-- name: CreateOrderHistoryItem :one
INSERT INTO order_history_items (
    history_id,
    change_type,
    product_code,
    product_name,
    old_quantity,
    new_quantity,
    old_reserved_quantity,
    new_reserved_quantity
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, history_id, change_type, product_code, product_name, old_quantity, new_quantity, old_reserved_quantity, new_reserved_quantity
`

type CreateOrderHistoryItemParams struct {
	HistoryID           int64    `json:"history_id"`
	ChangeType          string   `json:"change_type"`
	ProductCode         string   `json:"product_code"`
	ProductName         string   `json:"product_name"`
	OldQuantity         *float64 `json:"old_quantity"`
	NewQuantity         *float64 `json:"new_quantity"`
	OldReservedQuantity *float64 `json:"old_reserved_quantity"`
	NewReservedQuantity *float64 `json:"new_reserved_quantity"`
}

func (q *Queries) CreateOrderHistoryItem(ctx context.Context, arg CreateOrderHistoryItemParams) (OrderHistoryItem, error) {
	row := q.db.QueryRow(ctx, createOrderHistoryItem,
		arg.HistoryID,
		arg.ChangeType,
		arg.ProductCode,
		arg.ProductName,
		arg.OldQuantity,
		arg.NewQuantity,
		arg.OldReservedQuantity,
		arg.NewReservedQuantity,
	)
	var i OrderHistoryItem
	err := row.Scan(
		&i.ID,
		&i.HistoryID,
		&i.ChangeType,
		&i.ProductCode,
		&i.ProductName,
		&i.OldQuantity,
		&i.NewQuantity,
		&i.OldReservedQuantity,
		&i.NewReservedQuantity,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    iiko_product_id,
    product_name,
    quantity,
    reserved_quantity
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, order_id, iiko_product_id, product_name, quantity, reserved_quantity
`

type CreateOrderItemParams struct {
	OrderID          int64   `json:"order_id"`
	IikoProductID    *string `json:"iiko_product_id"`
	ProductName      string  `json:"product_name"`
	Quantity         float64 `json:"quantity"`
	ReservedQuantity float64 `json:"reserved_quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.IikoProductID,
		arg.ProductName,
		arg.Quantity,
		arg.ReservedQuantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.IikoProductID,
		&i.ProductName,
		&i.Quantity,
		&i.ReservedQuantity,
	)
	return i, err
}

const deleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
DELETE FROM order_items
WHERE order_id = $1
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deleteOrderItemsByOrderID, orderID)
	return err
}

const deleteOrdersCreatedBefore = `-- name: DeleteOrdersCreatedBefore :one
WITH deleted AS (
    DELETE FROM orders
    WHERE created_at < $1
      AND is_favorite = FALSE
    RETURNING id
)
SELECT COUNT(*)::BIGINT
FROM deleted
`

func (q *Queries) DeleteOrdersCreatedBefore(ctx context.Context, createdAtBefore pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, deleteOrdersCreatedBefore, createdAtBefore)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, number, location, created_at, from_department_id, to_department_id, fulfillment_date, created_by_username, comments, is_favorite
FROM orders
WHERE number = $1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, number string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, number)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
		&i.FulfillmentDate,
		&i.CreatedByUsername,
		&i.Comments,
		&i.IsFavorite,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT
    oi.id,
    oi.order_id,
    oi.iiko_product_id,
    oi.product_name,
    oi.quantity,
    oi.reserved_quantity,
    COALESCE(p.code, '') AS product_code
FROM order_items AS oi
LEFT JOIN iiko_products AS p ON p.id = oi.iiko_product_id
WHERE oi.order_id = $1
ORDER BY oi.id
`

type GetOrderItemsByOrderIDRow struct {
	ID               int64   `json:"id"`
	OrderID          int64   `json:"order_id"`
	IikoProductID    *string `json:"iiko_product_id"`
	ProductName      string  `json:"product_name"`
	Quantity         float64 `json:"quantity"`
	ReservedQuantity float64 `json:"reserved_quantity"`
	ProductCode      string  `json:"product_code"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.IikoProductID,
			&i.ProductName,
			&i.Quantity,
			&i.ReservedQuantity,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemsByOrderIDs = `-- name: GetOrderItemsByOrderIDs :many
SELECT
    oi.id,
    oi.order_id,
    oi.iiko_product_id,
    oi.product_name,
    oi.quantity,
    oi.reserved_quantity,
    COALESCE(p.code, '') AS product_code
FROM order_items AS oi
LEFT JOIN iiko_products AS p ON p.id = oi.iiko_product_id
WHERE oi.order_id = ANY($1::BIGINT[])
ORDER BY oi.order_id, oi.id
`

type GetOrderItemsByOrderIDsRow struct {
	ID               int64   `json:"id"`
	OrderID          int64   `json:"order_id"`
	IikoProductID    *string `json:"iiko_product_id"`
	ProductName      string  `json:"product_name"`
	Quantity         float64 `json:"quantity"`
	ReservedQuantity float64 `json:"reserved_quantity"`
	ProductCode      string  `json:"product_code"`
}

func (q *Queries) GetOrderItemsByOrderIDs(ctx context.Context, orderIds []int64) ([]GetOrderItemsByOrderIDsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderIDs, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDsRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.IikoProductID,
			&i.ProductName,
			&i.Quantity,
			&i.ReservedQuantity,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderHistoryByOrderID = `-- name: ListOrderHistoryByOrderID :many
SELECT id, order_id, changed_by_username, changed_at
FROM order_history
WHERE order_id = $1
ORDER BY changed_at DESC, id DESC
`

func (q *Queries) ListOrderHistoryByOrderID(ctx context.Context, orderID int64) ([]OrderHistory, error) {
	rows, err := q.db.Query(ctx, listOrderHistoryByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderHistory
	for rows.Next() {
		var i OrderHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ChangedByUsername,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderHistoryItemsByHistoryID = `-- name: ListOrderHistoryItemsByHistoryID :many
SELECT id, history_id, change_type, product_code, product_name, old_quantity, new_quantity, old_reserved_quantity, new_reserved_quantity
FROM order_history_items
WHERE history_id = $1
ORDER BY id
`

func (q *Queries) ListOrderHistoryItemsByHistoryID(ctx context.Context, historyID int64) ([]OrderHistoryItem, error) {
	rows, err := q.db.Query(ctx, listOrderHistoryItemsByHistoryID, historyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderHistoryItem
	for rows.Next() {
		var i OrderHistoryItem
		if err := rows.Scan(
			&i.ID,
			&i.HistoryID,
			&i.ChangeType,
			&i.ProductCode,
			&i.ProductName,
			&i.OldQuantity,
			&i.NewQuantity,
			&i.OldReservedQuantity,
			&i.NewReservedQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, number, location, created_at, from_department_id, to_department_id, fulfillment_date, created_by_username, comments, is_favorite
FROM orders
WHERE
    ($1::BIGINT IS NULL OR from_department_id = $1::BIGINT)
    AND ($2::DATE IS NULL OR fulfillment_date = $2::DATE)
ORDER BY id DESC
LIMIT $4
OFFSET $3
`

type ListOrdersParams struct {
	FromDepartmentID *int64      `json:"from_department_id"`
	FulfillmentDate  pgtype.Date `json:"fulfillment_date"`
	OrderOffset      int32       `json:"order_offset"`
	OrderLimit       int32       `json:"order_limit"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.FromDepartmentID,
		arg.FulfillmentDate,
		arg.OrderOffset,
		arg.OrderLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Location,
			&i.CreatedAt,
			&i.FromDepartmentID,
			&i.ToDepartmentID,
			&i.FulfillmentDate,
			&i.CreatedByUsername,
			&i.Comments,
			&i.IsFavorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderCounter = `-- name: NextOrderCounter :one
UPDATE order_counters
SET counter = counter + 1
WHERE day = $1 AND department_id = $2
RETURNING counter
`

type NextOrderCounterParams struct {
	Day          string `json:"day"`
	DepartmentID int64  `json:"department_id"`
}

func (q *Queries) NextOrderCounter(ctx context.Context, arg NextOrderCounterParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrderCounter, arg.Day, arg.DepartmentID)
	var counter int64
	err := row.Scan(&counter)
	return counter, err
}

const setOrderFavorite = `-- name: SetOrderFavorite :one
UPDATE orders
SET is_favorite = $1
WHERE number = $2
RETURNING id, number, location, created_at, from_department_id, to_department_id, fulfillment_date, created_by_username, comments, is_favorite
`

type SetOrderFavoriteParams struct {
	IsFavorite bool   `json:"is_favorite"`
	Number     string `json:"number"`
}

func (q *Queries) SetOrderFavorite(ctx context.Context, arg SetOrderFavoriteParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderFavorite, arg.IsFavorite, arg.Number)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
		&i.FulfillmentDate,
		&i.CreatedByUsername,
		&i.Comments,
		&i.IsFavorite,
	)
	return i, err
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET
    from_department_id = $1,
    to_department_id = $2,
    fulfillment_date = $3,
    comments = $4
WHERE number = $5
RETURNING id, number, location, created_at, from_department_id, to_department_id, fulfillment_date, created_by_username, comments, is_favorite
`

type UpdateOrderParams struct {
	FromDepartmentID *int64      `json:"from_department_id"`
	ToDepartmentID   *int64      `json:"to_department_id"`
	FulfillmentDate  pgtype.Date `json:"fulfillment_date"`
	Comments         []byte      `json:"comments"`
	Number           string      `json:"number"`
}

// created_by_username is intentionally left untouched: editing an order keeps
// its original author; who made each change is recorded in order_history.
func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.FromDepartmentID,
		arg.ToDepartmentID,
		arg.FulfillmentDate,
		arg.Comments,
		arg.Number,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
		&i.FulfillmentDate,
		&i.CreatedByUsername,
		&i.Comments,
		&i.IsFavorite,
	)
	return i, err
}
