// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
)

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*)
FROM orders
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    number,
    location,
    from_department_id,
    to_department_id,
    created_at,
    fulfillment_date,
    created_by_username
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, number, location, created_at, from_department_id, to_department_id, fulfillment_date, created_by_username
`

type CreateOrderParams struct {
	Number            string `json:"number"`
	Location          string `json:"location"`
	FromDepartmentID  *int64 `json:"from_department_id"`
	ToDepartmentID    *int64 `json:"to_department_id"`
	CreatedAt         string `json:"created_at"`
	FulfillmentDate   string `json:"fulfillment_date"`
	CreatedByUsername string `json:"created_by_username"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Number,
		arg.Location,
		arg.FromDepartmentID,
		arg.ToDepartmentID,
		arg.CreatedAt,
		arg.FulfillmentDate,
		arg.CreatedByUsername,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
		&i.FulfillmentDate,
		&i.CreatedByUsername,
	)
	return i, err
}

const createOrderCounterDay = `-- name: CreateOrderCounterDay :exec
INSERT INTO order_counters(day, counter)
VALUES ($1, 0)
ON CONFLICT(day) DO NOTHING
`

func (q *Queries) CreateOrderCounterDay(ctx context.Context, day string) error {
	_, err := q.db.Exec(ctx, createOrderCounterDay, day)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    iiko_product_id,
    product_name,
    quantity,
    reserved_quantity
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, order_id, iiko_product_id, product_name, quantity, reserved_quantity
`

type CreateOrderItemParams struct {
	OrderID          int64   `json:"order_id"`
	IikoProductID    *string `json:"iiko_product_id"`
	ProductName      string  `json:"product_name"`
	Quantity         float64 `json:"quantity"`
	ReservedQuantity float64 `json:"reserved_quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.IikoProductID,
		arg.ProductName,
		arg.Quantity,
		arg.ReservedQuantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.IikoProductID,
		&i.ProductName,
		&i.Quantity,
		&i.ReservedQuantity,
	)
	return i, err
}

const createOrderTemplate = `-- name: CreateOrderTemplate :one
INSERT INTO order_templates (
    theme,
    name,
    body,
    created_by_user_id,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, theme, name, body, created_by_user_id, created_at, updated_at
`

type CreateOrderTemplateParams struct {
	Theme           string `json:"theme"`
	Name            string `json:"name"`
	Body            string `json:"body"`
	CreatedByUserID *int64 `json:"created_by_user_id"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) CreateOrderTemplate(ctx context.Context, arg CreateOrderTemplateParams) (OrderTemplate, error) {
	row := q.db.QueryRow(ctx, createOrderTemplate,
		arg.Theme,
		arg.Name,
		arg.Body,
		arg.CreatedByUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OrderTemplate
	err := row.Scan(
		&i.ID,
		&i.Theme,
		&i.Name,
		&i.Body,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
DELETE FROM order_items
WHERE order_id = $1
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deleteOrderItemsByOrderID, orderID)
	return err
}

const deleteOrderTemplateByID = `-- name: DeleteOrderTemplateByID :exec
DELETE FROM order_templates
WHERE id = $1
`

func (q *Queries) DeleteOrderTemplateByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrderTemplateByID, id)
	return err
}

const deleteOrdersCreatedBefore = `-- name: DeleteOrdersCreatedBefore :one
WITH deleted AS (
    DELETE FROM orders
    WHERE created_at < $1
    RETURNING id
)
SELECT COUNT(*)::BIGINT
FROM deleted
`

func (q *Queries) DeleteOrdersCreatedBefore(ctx context.Context, createdAtBefore string) (int64, error) {
	row := q.db.QueryRow(ctx, deleteOrdersCreatedBefore, createdAtBefore)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, number, location, created_at, from_department_id, to_department_id, fulfillment_date, created_by_username
FROM orders
WHERE number = $1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, number string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, number)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
		&i.FulfillmentDate,
		&i.CreatedByUsername,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT
    oi.id,
    oi.order_id,
    oi.iiko_product_id,
    oi.product_name,
    oi.quantity,
    oi.reserved_quantity,
    COALESCE(p.code, '') AS product_code
FROM order_items AS oi
LEFT JOIN iiko_products AS p ON p.id = oi.iiko_product_id
WHERE oi.order_id = $1
ORDER BY oi.id
`

type GetOrderItemsByOrderIDRow struct {
	ID               int64   `json:"id"`
	OrderID          int64   `json:"order_id"`
	IikoProductID    *string `json:"iiko_product_id"`
	ProductName      string  `json:"product_name"`
	Quantity         float64 `json:"quantity"`
	ReservedQuantity float64 `json:"reserved_quantity"`
	ProductCode      string  `json:"product_code"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.IikoProductID,
			&i.ProductName,
			&i.Quantity,
			&i.ReservedQuantity,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderTemplateByID = `-- name: GetOrderTemplateByID :one
SELECT id, theme, name, body, created_by_user_id, created_at, updated_at
FROM order_templates
WHERE id = $1
`

func (q *Queries) GetOrderTemplateByID(ctx context.Context, id int64) (OrderTemplate, error) {
	row := q.db.QueryRow(ctx, getOrderTemplateByID, id)
	var i OrderTemplate
	err := row.Scan(
		&i.ID,
		&i.Theme,
		&i.Name,
		&i.Body,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderTemplates = `-- name: ListOrderTemplates :many
SELECT id, theme, name, body, created_by_user_id, created_at, updated_at
FROM order_templates
ORDER BY theme, name, id
`

func (q *Queries) ListOrderTemplates(ctx context.Context) ([]OrderTemplate, error) {
	rows, err := q.db.Query(ctx, listOrderTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderTemplate
	for rows.Next() {
		var i OrderTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Theme,
			&i.Name,
			&i.Body,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, number, location, created_at, from_department_id, to_department_id, fulfillment_date, created_by_username
FROM orders
ORDER BY id DESC
LIMIT $2
OFFSET $1
`

type ListOrdersParams struct {
	OrderOffset int32 `json:"order_offset"`
	OrderLimit  int32 `json:"order_limit"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.OrderOffset, arg.OrderLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Location,
			&i.CreatedAt,
			&i.FromDepartmentID,
			&i.ToDepartmentID,
			&i.FulfillmentDate,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderCounter = `-- name: NextOrderCounter :one
UPDATE order_counters
SET counter = counter + 1
WHERE day = $1
RETURNING counter
`

func (q *Queries) NextOrderCounter(ctx context.Context, day string) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrderCounter, day)
	var counter int64
	err := row.Scan(&counter)
	return counter, err
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET
    from_department_id = $1,
    to_department_id = $2,
    fulfillment_date = $3,
    created_by_username = $4
WHERE number = $5
RETURNING id, number, location, created_at, from_department_id, to_department_id, fulfillment_date, created_by_username
`

type UpdateOrderParams struct {
	FromDepartmentID  *int64 `json:"from_department_id"`
	ToDepartmentID    *int64 `json:"to_department_id"`
	FulfillmentDate   string `json:"fulfillment_date"`
	CreatedByUsername string `json:"created_by_username"`
	Number            string `json:"number"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.FromDepartmentID,
		arg.ToDepartmentID,
		arg.FulfillmentDate,
		arg.CreatedByUsername,
		arg.Number,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
		&i.FulfillmentDate,
		&i.CreatedByUsername,
	)
	return i, err
}
