// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    number,
    location,
    from_department_id,
    to_department_id,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, number, location, created_at, from_department_id, to_department_id
`

type CreateOrderParams struct {
	Number           string `json:"number"`
	Location         string `json:"location"`
	FromDepartmentID *int64 `json:"from_department_id"`
	ToDepartmentID   *int64 `json:"to_department_id"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Number,
		arg.Location,
		arg.FromDepartmentID,
		arg.ToDepartmentID,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
	)
	return i, err
}

const createOrderCounterDay = `-- name: CreateOrderCounterDay :exec
INSERT INTO order_counters(day, counter)
VALUES ($1, 0)
ON CONFLICT(day) DO NOTHING
`

func (q *Queries) CreateOrderCounterDay(ctx context.Context, day string) error {
	_, err := q.db.Exec(ctx, createOrderCounterDay, day)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    iiko_product_id,
    product_name,
    quantity
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, order_id, iiko_product_id, product_name, quantity
`

type CreateOrderItemParams struct {
	OrderID       int64   `json:"order_id"`
	IikoProductID *string `json:"iiko_product_id"`
	ProductName   string  `json:"product_name"`
	Quantity      float64 `json:"quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.IikoProductID,
		arg.ProductName,
		arg.Quantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.IikoProductID,
		&i.ProductName,
		&i.Quantity,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, number, location, created_at, from_department_id, to_department_id
FROM orders
WHERE number = $1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, number string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, number)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT
    oi.id,
    oi.order_id,
    oi.iiko_product_id,
    oi.product_name,
    oi.quantity,
    COALESCE(p.code, '') AS product_code
FROM order_items AS oi
LEFT JOIN iiko_products AS p ON p.id = oi.iiko_product_id
WHERE oi.order_id = $1
ORDER BY oi.id
`

type GetOrderItemsByOrderIDRow struct {
	ID            int64   `json:"id"`
	OrderID       int64   `json:"order_id"`
	IikoProductID *string `json:"iiko_product_id"`
	ProductName   string  `json:"product_name"`
	Quantity      float64 `json:"quantity"`
	ProductCode   string  `json:"product_code"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.IikoProductID,
			&i.ProductName,
			&i.Quantity,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, number, location, created_at, from_department_id, to_department_id
FROM orders
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListOrders(ctx context.Context, orderLimit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, orderLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Location,
			&i.CreatedAt,
			&i.FromDepartmentID,
			&i.ToDepartmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderCounter = `-- name: NextOrderCounter :one
UPDATE order_counters
SET counter = counter + 1
WHERE day = $1
RETURNING counter
`

func (q *Queries) NextOrderCounter(ctx context.Context, day string) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrderCounter, day)
	var counter int64
	err := row.Scan(&counter)
	return counter, err
}
