// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_drafts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOrderDraft = `-- name: DeleteOrderDraft :exec
DELETE FROM order_drafts
WHERE created_by_username = $1
  AND category_id = $2
`

type DeleteOrderDraftParams struct {
	CreatedByUsername string `json:"created_by_username"`
	CategoryID        int64  `json:"category_id"`
}

func (q *Queries) DeleteOrderDraft(ctx context.Context, arg DeleteOrderDraftParams) error {
	_, err := q.db.Exec(ctx, deleteOrderDraft, arg.CreatedByUsername, arg.CategoryID)
	return err
}

const deleteOrderDraftsOlderThan = `-- name: DeleteOrderDraftsOlderThan :one
WITH deleted AS (
    DELETE FROM order_drafts
    WHERE updated_at < $1
    RETURNING id
)
SELECT COUNT(*)::BIGINT
FROM deleted
`

func (q *Queries) DeleteOrderDraftsOlderThan(ctx context.Context, updatedAtBefore pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, deleteOrderDraftsOlderThan, updatedAtBefore)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrderDraft = `-- name: GetOrderDraft :one
SELECT id, created_by_username, category_id, from_department_id, fulfillment_date, comments, items, updated_at
FROM order_drafts
WHERE created_by_username = $1
  AND category_id = $2
`

type GetOrderDraftParams struct {
	CreatedByUsername string `json:"created_by_username"`
	CategoryID        int64  `json:"category_id"`
}

func (q *Queries) GetOrderDraft(ctx context.Context, arg GetOrderDraftParams) (OrderDraft, error) {
	row := q.db.QueryRow(ctx, getOrderDraft, arg.CreatedByUsername, arg.CategoryID)
	var i OrderDraft
	err := row.Scan(
		&i.ID,
		&i.CreatedByUsername,
		&i.CategoryID,
		&i.FromDepartmentID,
		&i.FulfillmentDate,
		&i.Comments,
		&i.Items,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderDrafts = `-- name: ListOrderDrafts :many
SELECT id, created_by_username, category_id, from_department_id, fulfillment_date, comments, items, updated_at
FROM order_drafts
WHERE created_by_username = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListOrderDrafts(ctx context.Context, createdByUsername string) ([]OrderDraft, error) {
	rows, err := q.db.Query(ctx, listOrderDrafts, createdByUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderDraft
	for rows.Next() {
		var i OrderDraft
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUsername,
			&i.CategoryID,
			&i.FromDepartmentID,
			&i.FulfillmentDate,
			&i.Comments,
			&i.Items,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrderDraft = `-- name: UpsertOrderDraft :one
INSERT INTO order_drafts (
    created_by_username,
    category_id,
    from_department_id,
    fulfillment_date,
    comments,
    items,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    now()
)
ON CONFLICT (created_by_username, category_id) DO UPDATE SET
    from_department_id = EXCLUDED.from_department_id,
    fulfillment_date = EXCLUDED.fulfillment_date,
    comments = EXCLUDED.comments,
    items = EXCLUDED.items,
    updated_at = now()
RETURNING id, created_by_username, category_id, from_department_id, fulfillment_date, comments, items, updated_at
`

type UpsertOrderDraftParams struct {
	CreatedByUsername string      `json:"created_by_username"`
	CategoryID        int64       `json:"category_id"`
	FromDepartmentID  *int64      `json:"from_department_id"`
	FulfillmentDate   pgtype.Date `json:"fulfillment_date"`
	Comments          []byte      `json:"comments"`
	Items             []byte      `json:"items"`
}

func (q *Queries) UpsertOrderDraft(ctx context.Context, arg UpsertOrderDraftParams) (OrderDraft, error) {
	row := q.db.QueryRow(ctx, upsertOrderDraft,
		arg.CreatedByUsername,
		arg.CategoryID,
		arg.FromDepartmentID,
		arg.FulfillmentDate,
		arg.Comments,
		arg.Items,
	)
	var i OrderDraft
	err := row.Scan(
		&i.ID,
		&i.CreatedByUsername,
		&i.CategoryID,
		&i.FromDepartmentID,
		&i.FulfillmentDate,
		&i.Comments,
		&i.Items,
		&i.UpdatedAt,
	)
	return i, err
}
