// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOrderOutboxEvent = `-- name: InsertOrderOutboxEvent :one
INSERT INTO order_outbox (
    aggregate_id,
    event_type,
    payload,
    correlation_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id
`

type InsertOrderOutboxEventParams struct {
	AggregateID   string `json:"aggregate_id"`
	EventType     string `json:"event_type"`
	Payload       []byte `json:"payload"`
	CorrelationID string `json:"correlation_id"`
}

func (q *Queries) InsertOrderOutboxEvent(ctx context.Context, arg InsertOrderOutboxEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrderOutboxEvent,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.CorrelationID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listUnpublishedOrderOutboxEvents = `-- name: ListUnpublishedOrderOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, correlation_id, created_at
FROM order_outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
`

type ListUnpublishedOrderOutboxEventsRow struct {
	ID            int64              `json:"id"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	CorrelationID string             `json:"correlation_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUnpublishedOrderOutboxEvents(ctx context.Context, maxEvents int32) ([]ListUnpublishedOrderOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOrderOutboxEvents, maxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnpublishedOrderOutboxEventsRow
	for rows.Next() {
		var i ListUnpublishedOrderOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CorrelationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderOutboxEventPublished = `-- name: MarkOrderOutboxEventPublished :exec
UPDATE order_outbox
SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOrderOutboxEventPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOrderOutboxEventPublished, id)
	return err
}
