// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyOrderProduction = `-- name: ApplyOrderProduction :exec
UPDATE order_items oi
SET produced_quantity = latest.produced,
    produced_reason = NULLIF(latest.reason, '')
FROM (
    SELECT DISTINCT ON (lower(trim(psi.product_name)))
        lower(trim(psi.product_name)) AS pname,
        psi.produced_quantity AS produced,
        psi.reason AS reason
    FROM production_sheet_items psi
    WHERE psi.order_id = $1
    ORDER BY lower(trim(psi.product_name)), psi.sheet_id DESC
) latest
WHERE oi.order_id = $1
  AND lower(trim(oi.product_name)) = latest.pname
`

// Проецирует журнал на заказ: для каждой позиции берётся значение из самого
// свежего листа (по id листа), позиции без записей в журнале сбрасываются.
func (q *Queries) ApplyOrderProduction(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, applyOrderProduction, orderID)
	return err
}

const clearUncoveredOrderProduction = `-- name: ClearUncoveredOrderProduction :exec
UPDATE order_items oi
SET produced_quantity = NULL,
    produced_reason = NULL
WHERE oi.order_id = $1
  AND NOT EXISTS (
      SELECT 1
      FROM production_sheet_items psi
      WHERE psi.order_id = oi.order_id
        AND lower(trim(psi.product_name)) = lower(trim(oi.product_name))
  )
`

func (q *Queries) ClearUncoveredOrderProduction(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, clearUncoveredOrderProduction, orderID)
	return err
}

const createProductionSheet = `-- name: CreateProductionSheet :one
INSERT INTO production_sheets (created_by_username)
VALUES ($1)
RETURNING id, created_by_username, created_at, updated_at
`

func (q *Queries) CreateProductionSheet(ctx context.Context, createdByUsername string) (ProductionSheet, error) {
	row := q.db.QueryRow(ctx, createProductionSheet, createdByUsername)
	var i ProductionSheet
	err := row.Scan(
		&i.ID,
		&i.CreatedByUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductionSheet = `-- name: DeleteProductionSheet :exec
DELETE FROM production_sheets
WHERE id = $1
`

func (q *Queries) DeleteProductionSheet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProductionSheet, id)
	return err
}

const deleteProductionSheetItems = `-- name: DeleteProductionSheetItems :exec
DELETE FROM production_sheet_items
WHERE sheet_id = $1
`

func (q *Queries) DeleteProductionSheetItems(ctx context.Context, sheetID int64) error {
	_, err := q.db.Exec(ctx, deleteProductionSheetItems, sheetID)
	return err
}

const getOrderProductionSheetID = `-- name: GetOrderProductionSheetID :one
SELECT sheet_id
FROM production_sheet_items
WHERE order_id = $1
ORDER BY sheet_id DESC
LIMIT 1
`

// Заказ принадлежит максимум одному листу отработки (1:N от листа к
// заказам); на случай исторических пересечений берётся самый свежий лист.
func (q *Queries) GetOrderProductionSheetID(ctx context.Context, orderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getOrderProductionSheetID, orderID)
	var sheet_id int64
	err := row.Scan(&sheet_id)
	return sheet_id, err
}

const getProductionSheet = `-- name: GetProductionSheet :one
SELECT id, created_by_username, created_at, updated_at
FROM production_sheets
WHERE id = $1
`

func (q *Queries) GetProductionSheet(ctx context.Context, id int64) (ProductionSheet, error) {
	row := q.db.QueryRow(ctx, getProductionSheet, id)
	var i ProductionSheet
	err := row.Scan(
		&i.ID,
		&i.CreatedByUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductionSheetItem = `-- name: InsertProductionSheetItem :exec
INSERT INTO production_sheet_items (sheet_id, order_id, product_name, produced_quantity, reason)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProductionSheetItemParams struct {
	SheetID          int64   `json:"sheet_id"`
	OrderID          int64   `json:"order_id"`
	ProductName      string  `json:"product_name"`
	ProducedQuantity float64 `json:"produced_quantity"`
	Reason           string  `json:"reason"`
}

func (q *Queries) InsertProductionSheetItem(ctx context.Context, arg InsertProductionSheetItemParams) error {
	_, err := q.db.Exec(ctx, insertProductionSheetItem,
		arg.SheetID,
		arg.OrderID,
		arg.ProductName,
		arg.ProducedQuantity,
		arg.Reason,
	)
	return err
}

const listProductionSheetItems = `-- name: ListProductionSheetItems :many
SELECT
    psi.id,
    psi.order_id,
    o.number AS order_number,
    psi.product_name,
    psi.produced_quantity,
    psi.reason
FROM production_sheet_items psi
JOIN orders o ON o.id = psi.order_id
WHERE psi.sheet_id = $1
ORDER BY psi.product_name, o.number
`

type ListProductionSheetItemsRow struct {
	ID               int64   `json:"id"`
	OrderID          int64   `json:"order_id"`
	OrderNumber      string  `json:"order_number"`
	ProductName      string  `json:"product_name"`
	ProducedQuantity float64 `json:"produced_quantity"`
	Reason           string  `json:"reason"`
}

func (q *Queries) ListProductionSheetItems(ctx context.Context, sheetID int64) ([]ListProductionSheetItemsRow, error) {
	rows, err := q.db.Query(ctx, listProductionSheetItems, sheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionSheetItemsRow
	for rows.Next() {
		var i ListProductionSheetItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.OrderNumber,
			&i.ProductName,
			&i.ProducedQuantity,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionSheetOrderIDs = `-- name: ListProductionSheetOrderIDs :many
SELECT DISTINCT order_id
FROM production_sheet_items
WHERE sheet_id = $1
`

func (q *Queries) ListProductionSheetOrderIDs(ctx context.Context, sheetID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listProductionSheetOrderIDs, sheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var order_id int64
		if err := rows.Scan(&order_id); err != nil {
			return nil, err
		}
		items = append(items, order_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionSheets = `-- name: ListProductionSheets :many
SELECT
    ps.id,
    ps.created_by_username,
    ps.created_at,
    ps.updated_at,
    COUNT(psi.id)::BIGINT AS item_count,
    COALESCE(ARRAY_AGG(DISTINCT o.number) FILTER (WHERE o.number IS NOT NULL), '{}')::TEXT[] AS order_numbers
FROM production_sheets ps
LEFT JOIN production_sheet_items psi ON psi.sheet_id = ps.id
LEFT JOIN orders o ON o.id = psi.order_id
GROUP BY ps.id
ORDER BY ps.id DESC
`

type ListProductionSheetsRow struct {
	ID                int64              `json:"id"`
	CreatedByUsername string             `json:"created_by_username"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ItemCount         int64              `json:"item_count"`
	OrderNumbers      []string           `json:"order_numbers"`
}

func (q *Queries) ListProductionSheets(ctx context.Context) ([]ListProductionSheetsRow, error) {
	rows, err := q.db.Query(ctx, listProductionSheets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionSheetsRow
	for rows.Next() {
		var i ListProductionSheetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUsername,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
			&i.OrderNumbers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchProductionSheet = `-- name: TouchProductionSheet :exec
UPDATE production_sheets
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchProductionSheet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchProductionSheet, id)
	return err
}
