// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductionSheet = `-- name: CreateProductionSheet :one
INSERT INTO production_sheets (created_by_username)
VALUES ($1)
RETURNING id, created_by_username, created_at, updated_at
`

func (q *Queries) CreateProductionSheet(ctx context.Context, createdByUsername string) (ProductionSheet, error) {
	row := q.db.QueryRow(ctx, createProductionSheet, createdByUsername)
	var i ProductionSheet
	err := row.Scan(
		&i.ID,
		&i.CreatedByUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductionSheet = `-- name: DeleteProductionSheet :exec
DELETE FROM production_sheets
WHERE id = $1
`

func (q *Queries) DeleteProductionSheet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProductionSheet, id)
	return err
}

const deleteProductionSheetItems = `-- name: DeleteProductionSheetItems :exec
DELETE FROM production_sheet_items
WHERE sheet_id = $1
`

func (q *Queries) DeleteProductionSheetItems(ctx context.Context, sheetID int64) error {
	_, err := q.db.Exec(ctx, deleteProductionSheetItems, sheetID)
	return err
}

const deleteProductionSheetOrders = `-- name: DeleteProductionSheetOrders :exec
DELETE FROM production_sheet_orders
WHERE sheet_id = $1
`

func (q *Queries) DeleteProductionSheetOrders(ctx context.Context, sheetID int64) error {
	_, err := q.db.Exec(ctx, deleteProductionSheetOrders, sheetID)
	return err
}

const getOrderProductionFacts = `-- name: GetOrderProductionFacts :many
SELECT DISTINCT ON (psi.order_id, lower(trim(psi.product_name)))
    psi.order_id,
    lower(trim(psi.product_name)) AS product_key,
    psi.produced_quantity,
    psi.reason
FROM production_sheet_items psi
WHERE psi.order_id = ANY($1::BIGINT[])
ORDER BY psi.order_id, lower(trim(psi.product_name)), psi.sheet_id DESC
`

type GetOrderProductionFactsRow struct {
	OrderID          int64   `json:"order_id"`
	ProductKey       string  `json:"product_key"`
	ProducedQuantity float64 `json:"produced_quantity"`
	Reason           string  `json:"reason"`
}

// Read-time декоратор: факт выпечки для позиций заказов из журнала (по
// каждой позиции побеждает самый свежий лист). Ключ — нормализованное имя.
func (q *Queries) GetOrderProductionFacts(ctx context.Context, orderIds []int64) ([]GetOrderProductionFactsRow, error) {
	rows, err := q.db.Query(ctx, getOrderProductionFacts, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderProductionFactsRow
	for rows.Next() {
		var i GetOrderProductionFactsRow
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductKey,
			&i.ProducedQuantity,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderProductionSheetID = `-- name: GetOrderProductionSheetID :one
SELECT sheet_id
FROM production_sheet_orders
WHERE order_id = $1
ORDER BY sheet_id DESC
LIMIT 1
`

// Заказ принадлежит максимум одному листу отработки (1:N от листа к
// заказам); на случай исторических пересечений берётся самый свежий лист.
// Принадлежность определяется сохранённым выбором, не отклонениями.
func (q *Queries) GetOrderProductionSheetID(ctx context.Context, orderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getOrderProductionSheetID, orderID)
	var sheet_id int64
	err := row.Scan(&sheet_id)
	return sheet_id, err
}

const getProductionSheet = `-- name: GetProductionSheet :one
SELECT id, created_by_username, created_at, updated_at
FROM production_sheets
WHERE id = $1
`

func (q *Queries) GetProductionSheet(ctx context.Context, id int64) (ProductionSheet, error) {
	row := q.db.QueryRow(ctx, getProductionSheet, id)
	var i ProductionSheet
	err := row.Scan(
		&i.ID,
		&i.CreatedByUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductionSheetItem = `-- name: InsertProductionSheetItem :exec
INSERT INTO production_sheet_items (sheet_id, order_id, product_name, produced_quantity, reason)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProductionSheetItemParams struct {
	SheetID          int64   `json:"sheet_id"`
	OrderID          int64   `json:"order_id"`
	ProductName      string  `json:"product_name"`
	ProducedQuantity float64 `json:"produced_quantity"`
	Reason           string  `json:"reason"`
}

func (q *Queries) InsertProductionSheetItem(ctx context.Context, arg InsertProductionSheetItemParams) error {
	_, err := q.db.Exec(ctx, insertProductionSheetItem,
		arg.SheetID,
		arg.OrderID,
		arg.ProductName,
		arg.ProducedQuantity,
		arg.Reason,
	)
	return err
}

const insertProductionSheetOrder = `-- name: InsertProductionSheetOrder :exec
INSERT INTO production_sheet_orders (sheet_id, order_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertProductionSheetOrderParams struct {
	SheetID int64 `json:"sheet_id"`
	OrderID int64 `json:"order_id"`
}

func (q *Queries) InsertProductionSheetOrder(ctx context.Context, arg InsertProductionSheetOrderParams) error {
	_, err := q.db.Exec(ctx, insertProductionSheetOrder, arg.SheetID, arg.OrderID)
	return err
}

const listOrderProductionSheetIDs = `-- name: ListOrderProductionSheetIDs :many
SELECT DISTINCT ON (order_id)
    order_id,
    sheet_id
FROM production_sheet_orders
WHERE order_id = ANY($1::BIGINT[])
ORDER BY order_id, sheet_id DESC
`

type ListOrderProductionSheetIDsRow struct {
	OrderID int64 `json:"order_id"`
	SheetID int64 `json:"sheet_id"`
}

// Пакетная версия для списка заказов: матрица должна видеть принадлежность
// к отработке без отдельного запроса на каждую карточку.
func (q *Queries) ListOrderProductionSheetIDs(ctx context.Context, orderIds []int64) ([]ListOrderProductionSheetIDsRow, error) {
	rows, err := q.db.Query(ctx, listOrderProductionSheetIDs, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderProductionSheetIDsRow
	for rows.Next() {
		var i ListOrderProductionSheetIDsRow
		if err := rows.Scan(&i.OrderID, &i.SheetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionSheetItems = `-- name: ListProductionSheetItems :many
SELECT
    psi.id,
    psi.order_id,
    o.number AS order_number,
    psi.product_name,
    psi.produced_quantity,
    psi.reason
FROM production_sheet_items psi
JOIN orders o ON o.id = psi.order_id
WHERE psi.sheet_id = $1
ORDER BY psi.product_name, o.number
`

type ListProductionSheetItemsRow struct {
	ID               int64   `json:"id"`
	OrderID          int64   `json:"order_id"`
	OrderNumber      string  `json:"order_number"`
	ProductName      string  `json:"product_name"`
	ProducedQuantity float64 `json:"produced_quantity"`
	Reason           string  `json:"reason"`
}

func (q *Queries) ListProductionSheetItems(ctx context.Context, sheetID int64) ([]ListProductionSheetItemsRow, error) {
	rows, err := q.db.Query(ctx, listProductionSheetItems, sheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionSheetItemsRow
	for rows.Next() {
		var i ListProductionSheetItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.OrderNumber,
			&i.ProductName,
			&i.ProducedQuantity,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionSheetOrderIDs = `-- name: ListProductionSheetOrderIDs :many
SELECT order_id
FROM production_sheet_orders
WHERE sheet_id = $1
`

func (q *Queries) ListProductionSheetOrderIDs(ctx context.Context, sheetID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listProductionSheetOrderIDs, sheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var order_id int64
		if err := rows.Scan(&order_id); err != nil {
			return nil, err
		}
		items = append(items, order_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionSheetOrderNumbers = `-- name: ListProductionSheetOrderNumbers :many
SELECT o.number
FROM production_sheet_orders pso
JOIN orders o ON o.id = pso.order_id
WHERE pso.sheet_id = $1
ORDER BY o.number
`

func (q *Queries) ListProductionSheetOrderNumbers(ctx context.Context, sheetID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listProductionSheetOrderNumbers, sheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var number string
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionSheets = `-- name: ListProductionSheets :many
SELECT
    ps.id,
    ps.created_by_username,
    ps.created_at,
    ps.updated_at,
    (
        SELECT COUNT(*)
        FROM production_sheet_items psi
        WHERE psi.sheet_id = ps.id
    )::BIGINT AS item_count,
    COALESCE((
        SELECT ARRAY_AGG(o.number ORDER BY o.number)
        FROM production_sheet_orders pso
        JOIN orders o ON o.id = pso.order_id
        WHERE pso.sheet_id = ps.id
    ), '{}')::TEXT[] AS order_numbers
FROM production_sheets ps
ORDER BY ps.id DESC
`

type ListProductionSheetsRow struct {
	ID                int64              `json:"id"`
	CreatedByUsername string             `json:"created_by_username"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ItemCount         int64              `json:"item_count"`
	OrderNumbers      []string           `json:"order_numbers"`
}

// order_numbers — сохранённый выбор партии (production_sheet_orders), а не
// заказы с отклонениями: лист покрывает партию целиком.
func (q *Queries) ListProductionSheets(ctx context.Context) ([]ListProductionSheetsRow, error) {
	rows, err := q.db.Query(ctx, listProductionSheets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionSheetsRow
	for rows.Next() {
		var i ListProductionSheetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUsername,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
			&i.OrderNumbers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchProductionSheet = `-- name: TouchProductionSheet :exec
UPDATE production_sheets
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchProductionSheet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchProductionSheet, id)
	return err
}
