// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"
)

const dishExistsByCode = `-- name: DishExistsByCode :one
SELECT COUNT(*)::bigint
FROM iiko_products
WHERE code = $1
  AND type = 'DISH'
`

func (q *Queries) DishExistsByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, dishExistsByCode, code)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getIikoProductByCode = `-- name: GetIikoProductByCode :one
SELECT
    id,
    code,
    name,
    type,
    measure_unit,
    raw_json
FROM iiko_products
WHERE code = $1
ORDER BY
    CASE WHEN type = 'DISH' THEN 0 ELSE 1 END,
    updated_at DESC,
    id
LIMIT 1
`

type GetIikoProductByCodeRow struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
}

func (q *Queries) GetIikoProductByCode(ctx context.Context, code string) (GetIikoProductByCodeRow, error) {
	row := q.db.QueryRow(ctx, getIikoProductByCode, code)
	var i GetIikoProductByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.MeasureUnit,
		&i.RawJson,
	)
	return i, err
}

const getIikoProductByID = `-- name: GetIikoProductByID :one
SELECT
    id,
    code,
    name,
    type,
    measure_unit,
    raw_json
FROM iiko_products
WHERE id = $1
`

type GetIikoProductByIDRow struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
}

func (q *Queries) GetIikoProductByID(ctx context.Context, id string) (GetIikoProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getIikoProductByID, id)
	var i GetIikoProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.MeasureUnit,
		&i.RawJson,
	)
	return i, err
}

const getIikoProductsByName = `-- name: GetIikoProductsByName :many
SELECT
    id,
    code,
    name,
    type,
    measure_unit,
    raw_json
FROM iiko_products
WHERE trim(name) = trim($1)
`

type GetIikoProductsByNameRow struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
}

func (q *Queries) GetIikoProductsByName(ctx context.Context, name string) ([]GetIikoProductsByNameRow, error) {
	rows, err := q.db.Query(ctx, getIikoProductsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIikoProductsByNameRow
	for rows.Next() {
		var i GetIikoProductsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.MeasureUnit,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
