// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDishCatalogItem = `-- name: DeleteDishCatalogItem :exec
DELETE FROM dish_catalog
WHERE code = $1
`

func (q *Queries) DeleteDishCatalogItem(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteDishCatalogItem, code)
	return err
}

const dishExistsByCode = `-- name: DishExistsByCode :one
SELECT COUNT(*)::bigint
FROM iiko_products
WHERE code = $1
  AND type = 'DISH'
`

func (q *Queries) DishExistsByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, dishExistsByCode, code)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureDishGroup = `-- name: EnsureDishGroup :one
INSERT INTO dish_groups (category_id, name)
VALUES ($1, $2)
ON CONFLICT (category_id, name) DO UPDATE SET updated_at = now()
RETURNING id
`

type EnsureDishGroupParams struct {
	CategoryID *int64 `json:"category_id"`
	Name       string `json:"name"`
}

// Find-or-create a group by (category, name); returns its id. The repo resolves
// a dish's group name to this id before upserting the dish.
// ponytail: UNIQUE(category_id, name) does not dedupe NULL-category groups
// (Postgres treats NULLs as distinct), so uncategorized groups can duplicate.
// Harmless — the UI groups by name — upgrade to NULLS NOT DISTINCT (PG15+) if it matters.
func (q *Queries) EnsureDishGroup(ctx context.Context, arg EnsureDishGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, ensureDishGroup, arg.CategoryID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getIikoProductByCode = `-- name: GetIikoProductByCode :one
SELECT
    id,
    code,
    name,
    type,
    measure_unit,
    raw_json
FROM iiko_products
WHERE code = $1
ORDER BY
    CASE WHEN type = 'DISH' THEN 0 ELSE 1 END,
    updated_at DESC,
    id
LIMIT 1
`

type GetIikoProductByCodeRow struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
}

func (q *Queries) GetIikoProductByCode(ctx context.Context, code string) (GetIikoProductByCodeRow, error) {
	row := q.db.QueryRow(ctx, getIikoProductByCode, code)
	var i GetIikoProductByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.MeasureUnit,
		&i.RawJson,
	)
	return i, err
}

const getIikoProductByID = `-- name: GetIikoProductByID :one
SELECT
    id,
    code,
    name,
    type,
    measure_unit,
    raw_json
FROM iiko_products
WHERE id = $1
`

type GetIikoProductByIDRow struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
}

func (q *Queries) GetIikoProductByID(ctx context.Context, id string) (GetIikoProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getIikoProductByID, id)
	var i GetIikoProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.MeasureUnit,
		&i.RawJson,
	)
	return i, err
}

const listDishCatalogItems = `-- name: ListDishCatalogItems :many
SELECT id, code, name, created_at, updated_at, sort_order, category_id, group_id
FROM dish_catalog
ORDER BY CASE WHEN sort_order = 0 THEN 1 ELSE 0 END, sort_order, id, name, code
`

func (q *Queries) ListDishCatalogItems(ctx context.Context) ([]DishCatalog, error) {
	rows, err := q.db.Query(ctx, listDishCatalogItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DishCatalog
	for rows.Next() {
		var i DishCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
			&i.CategoryID,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDishCatalogItemsByName = `-- name: ListDishCatalogItemsByName :many
SELECT id, code, name, created_at, updated_at, sort_order, category_id, group_id
FROM dish_catalog
WHERE lower(trim(name)) = lower(trim($1))
ORDER BY CASE WHEN sort_order = 0 THEN 1 ELSE 0 END, sort_order, id, name, code
`

func (q *Queries) ListDishCatalogItemsByName(ctx context.Context, name string) ([]DishCatalog, error) {
	rows, err := q.db.Query(ctx, listDishCatalogItemsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DishCatalog
	for rows.Next() {
		var i DishCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
			&i.CategoryID,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDishGroups = `-- name: ListDishGroups :many
SELECT id, category_id, name, sort_order
FROM dish_groups
ORDER BY sort_order, id
`

type ListDishGroupsRow struct {
	ID         int64  `json:"id"`
	CategoryID *int64 `json:"category_id"`
	Name       string `json:"name"`
	SortOrder  int64  `json:"sort_order"`
}

func (q *Queries) ListDishGroups(ctx context.Context) ([]ListDishGroupsRow, error) {
	rows, err := q.db.Query(ctx, listDishGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDishGroupsRow
	for rows.Next() {
		var i ListDishGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchIikoDishes = `-- name: SearchIikoDishes :many
SELECT id, code, name, measure_unit
FROM iiko_products
WHERE type = 'DISH'
  AND trim(code) <> ''
  AND (name ILIKE '%' || $1 || '%' OR code ILIKE '%' || $1 || '%')
ORDER BY name, code
LIMIT $2
`

type SearchIikoDishesParams struct {
	Query *string `json:"query"`
	Lim   int32   `json:"lim"`
}

type SearchIikoDishesRow struct {
	ID          string `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	MeasureUnit string `json:"measure_unit"`
}

func (q *Queries) SearchIikoDishes(ctx context.Context, arg SearchIikoDishesParams) ([]SearchIikoDishesRow, error) {
	rows, err := q.db.Query(ctx, searchIikoDishes, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchIikoDishesRow
	for rows.Next() {
		var i SearchIikoDishesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.MeasureUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDishCatalogSortOrder = `-- name: SetDishCatalogSortOrder :exec
UPDATE dish_catalog SET
    sort_order = $1,
    updated_at = $2
WHERE code = $3
`

type SetDishCatalogSortOrderParams struct {
	SortOrder int64              `json:"sort_order"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Code      string             `json:"code"`
}

func (q *Queries) SetDishCatalogSortOrder(ctx context.Context, arg SetDishCatalogSortOrderParams) error {
	_, err := q.db.Exec(ctx, setDishCatalogSortOrder, arg.SortOrder, arg.UpdatedAt, arg.Code)
	return err
}

const updateDishCatalogItem = `-- name: UpdateDishCatalogItem :one
UPDATE dish_catalog SET
    code = $1,
    name = $2,
    group_id = $3,
    category_id = $4,
    sort_order = $5,
    updated_at = $6
WHERE code = $7
RETURNING id, code, name, created_at, updated_at, sort_order, category_id, group_id
`

type UpdateDishCatalogItemParams struct {
	NewCode    string             `json:"new_code"`
	Name       string             `json:"name"`
	GroupID    *int64             `json:"group_id"`
	CategoryID *int64             `json:"category_id"`
	SortOrder  int64              `json:"sort_order"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Code       string             `json:"code"`
}

func (q *Queries) UpdateDishCatalogItem(ctx context.Context, arg UpdateDishCatalogItemParams) (DishCatalog, error) {
	row := q.db.QueryRow(ctx, updateDishCatalogItem,
		arg.NewCode,
		arg.Name,
		arg.GroupID,
		arg.CategoryID,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.Code,
	)
	var i DishCatalog
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
		&i.CategoryID,
		&i.GroupID,
	)
	return i, err
}

const upsertDishCatalogItem = `-- name: UpsertDishCatalogItem :one
INSERT INTO dish_catalog (
    code,
    name,
    group_id,
    category_id,
    sort_order,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (code) DO UPDATE SET
    name = excluded.name,
    group_id = COALESCE(excluded.group_id, dish_catalog.group_id),
    category_id = COALESCE(dish_catalog.category_id, excluded.category_id),
    sort_order = excluded.sort_order,
    updated_at = excluded.updated_at
RETURNING id, code, name, created_at, updated_at, sort_order, category_id, group_id
`

type UpsertDishCatalogItemParams struct {
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	GroupID    *int64             `json:"group_id"`
	CategoryID *int64             `json:"category_id"`
	SortOrder  int64              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// category_id keeps an already-assigned category on conflict, so re-seeding
// from templates/dishes.txt never clobbers the admin's assignment.
func (q *Queries) UpsertDishCatalogItem(ctx context.Context, arg UpsertDishCatalogItemParams) (DishCatalog, error) {
	row := q.db.QueryRow(ctx, upsertDishCatalogItem,
		arg.Code,
		arg.Name,
		arg.GroupID,
		arg.CategoryID,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DishCatalog
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
		&i.CategoryID,
		&i.GroupID,
	)
	return i, err
}
