// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDishCatalogItem = `-- name: DeleteDishCatalogItem :exec
DELETE FROM dish_catalog
WHERE code = $1
`

func (q *Queries) DeleteDishCatalogItem(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteDishCatalogItem, code)
	return err
}

const dishExistsByCode = `-- name: DishExistsByCode :one
SELECT COUNT(*)::bigint
FROM iiko_products
WHERE code = $1
  AND type = 'DISH'
`

func (q *Queries) DishExistsByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, dishExistsByCode, code)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getIikoProductByCode = `-- name: GetIikoProductByCode :one
SELECT
    id,
    code,
    name,
    type,
    measure_unit,
    raw_json
FROM iiko_products
WHERE code = $1
ORDER BY
    CASE WHEN type = 'DISH' THEN 0 ELSE 1 END,
    updated_at DESC,
    id
LIMIT 1
`

type GetIikoProductByCodeRow struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
}

func (q *Queries) GetIikoProductByCode(ctx context.Context, code string) (GetIikoProductByCodeRow, error) {
	row := q.db.QueryRow(ctx, getIikoProductByCode, code)
	var i GetIikoProductByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.MeasureUnit,
		&i.RawJson,
	)
	return i, err
}

const getIikoProductByID = `-- name: GetIikoProductByID :one
SELECT
    id,
    code,
    name,
    type,
    measure_unit,
    raw_json
FROM iiko_products
WHERE id = $1
`

type GetIikoProductByIDRow struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
}

func (q *Queries) GetIikoProductByID(ctx context.Context, id string) (GetIikoProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getIikoProductByID, id)
	var i GetIikoProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.MeasureUnit,
		&i.RawJson,
	)
	return i, err
}

const getIikoProductsByName = `-- name: GetIikoProductsByName :many
SELECT
    id,
    code,
    name,
    type,
    measure_unit,
    raw_json
FROM iiko_products
WHERE trim(name) = trim($1)
`

type GetIikoProductsByNameRow struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	MeasureUnit string  `json:"measure_unit"`
	RawJson     string  `json:"raw_json"`
}

func (q *Queries) GetIikoProductsByName(ctx context.Context, name string) ([]GetIikoProductsByNameRow, error) {
	rows, err := q.db.Query(ctx, getIikoProductsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIikoProductsByNameRow
	for rows.Next() {
		var i GetIikoProductsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.MeasureUnit,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDishCatalogItems = `-- name: ListDishCatalogItems :many
SELECT id, code, name, theme, created_at, updated_at, sort_order
FROM dish_catalog
ORDER BY CASE WHEN sort_order = 0 THEN 1 ELSE 0 END, sort_order, id, theme, name, code
`

func (q *Queries) ListDishCatalogItems(ctx context.Context) ([]DishCatalog, error) {
	rows, err := q.db.Query(ctx, listDishCatalogItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DishCatalog
	for rows.Next() {
		var i DishCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Theme,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDishCatalogItemsByName = `-- name: ListDishCatalogItemsByName :many
SELECT id, code, name, theme, created_at, updated_at, sort_order
FROM dish_catalog
WHERE lower(trim(name)) = lower(trim($1))
ORDER BY CASE WHEN sort_order = 0 THEN 1 ELSE 0 END, sort_order, id, theme, name, code
`

func (q *Queries) ListDishCatalogItemsByName(ctx context.Context, name string) ([]DishCatalog, error) {
	rows, err := q.db.Query(ctx, listDishCatalogItemsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DishCatalog
	for rows.Next() {
		var i DishCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Theme,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIikoDishes = `-- name: ListIikoDishes :many
SELECT id, code, name, measure_unit
FROM iiko_products
WHERE type = 'DISH' AND trim(code) <> ''
ORDER BY name, code
`

type ListIikoDishesRow struct {
	ID          string `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	MeasureUnit string `json:"measure_unit"`
}

func (q *Queries) ListIikoDishes(ctx context.Context) ([]ListIikoDishesRow, error) {
	rows, err := q.db.Query(ctx, listIikoDishes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIikoDishesRow
	for rows.Next() {
		var i ListIikoDishesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.MeasureUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDishCatalogSortOrder = `-- name: SetDishCatalogSortOrder :exec
UPDATE dish_catalog SET
    sort_order = $1,
    updated_at = $2
WHERE code = $3
`

type SetDishCatalogSortOrderParams struct {
	SortOrder int64              `json:"sort_order"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Code      string             `json:"code"`
}

func (q *Queries) SetDishCatalogSortOrder(ctx context.Context, arg SetDishCatalogSortOrderParams) error {
	_, err := q.db.Exec(ctx, setDishCatalogSortOrder, arg.SortOrder, arg.UpdatedAt, arg.Code)
	return err
}

const updateDishCatalogItem = `-- name: UpdateDishCatalogItem :one
UPDATE dish_catalog SET
    code = $1,
    name = $2,
    theme = $3,
    sort_order = $4,
    updated_at = $5
WHERE code = $6
RETURNING id, code, name, theme, created_at, updated_at, sort_order
`

type UpdateDishCatalogItemParams struct {
	NewCode   string             `json:"new_code"`
	Name      string             `json:"name"`
	Theme     string             `json:"theme"`
	SortOrder int64              `json:"sort_order"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Code      string             `json:"code"`
}

func (q *Queries) UpdateDishCatalogItem(ctx context.Context, arg UpdateDishCatalogItemParams) (DishCatalog, error) {
	row := q.db.QueryRow(ctx, updateDishCatalogItem,
		arg.NewCode,
		arg.Name,
		arg.Theme,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.Code,
	)
	var i DishCatalog
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
	)
	return i, err
}

const upsertDishCatalogItem = `-- name: UpsertDishCatalogItem :one
INSERT INTO dish_catalog (
    code,
    name,
    theme,
    sort_order,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (code) DO UPDATE SET
    name = excluded.name,
    theme = excluded.theme,
    sort_order = excluded.sort_order,
    updated_at = excluded.updated_at
RETURNING id, code, name, theme, created_at, updated_at, sort_order
`

type UpsertDishCatalogItemParams struct {
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Theme     string             `json:"theme"`
	SortOrder int64              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertDishCatalogItem(ctx context.Context, arg UpsertDishCatalogItemParams) (DishCatalog, error) {
	row := q.db.QueryRow(ctx, upsertDishCatalogItem,
		arg.Code,
		arg.Name,
		arg.Theme,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DishCatalog
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
	)
	return i, err
}
