// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AssignUserDepartment(ctx context.Context, arg AssignUserDepartmentParams) (AuthUser, error)
	CountOrders(ctx context.Context) (int64, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateIikoSyncRun(ctx context.Context, arg CreateIikoSyncRunParams) (IikoSyncRun, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderCounterDay(ctx context.Context, day string) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOrderTemplate(ctx context.Context, arg CreateOrderTemplateParams) (OrderTemplate, error)
	CreatePasswordAuthUser(ctx context.Context, arg CreatePasswordAuthUserParams) (AuthUser, error)
	DeleteIikoAssemblyChartItemsByChartID(ctx context.Context, chartID string) error
	DeleteIikoPreparedChartItemsByChartID(ctx context.Context, preparedChartID string) error
	DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error
	DeleteOrderTemplateByID(ctx context.Context, id int64) error
	DishExistsByCode(ctx context.Context, code string) (int64, error)
	FinishIikoSyncRun(ctx context.Context, arg FinishIikoSyncRunParams) (IikoSyncRun, error)
	GetActiveAssemblyChartByProductID(ctx context.Context, arg GetActiveAssemblyChartByProductIDParams) (GetActiveAssemblyChartByProductIDRow, error)
	GetActiveAssemblyChartFullByProductID(ctx context.Context, arg GetActiveAssemblyChartFullByProductIDParams) (IikoAssemblyChart, error)
	GetActivePreparedChartFullByProductID(ctx context.Context, arg GetActivePreparedChartFullByProductIDParams) (IikoPreparedChart, error)
	GetAuthUserByTelegramID(ctx context.Context, telegramID *int64) (AuthUser, error)
	GetAuthUserByUsername(ctx context.Context, username string) (AuthUser, error)
	GetDepartmentByCode(ctx context.Context, code string) (Department, error)
	GetDepartmentByID(ctx context.Context, id int64) (Department, error)
	GetIikoProductByCode(ctx context.Context, code string) (GetIikoProductByCodeRow, error)
	GetIikoProductByID(ctx context.Context, id string) (GetIikoProductByIDRow, error)
	GetIikoProductsByName(ctx context.Context, name string) ([]GetIikoProductsByNameRow, error)
	GetOrderByNumber(ctx context.Context, number string) (Order, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDRow, error)
	GetOrderTemplateByID(ctx context.Context, id int64) (OrderTemplate, error)
	InsertIikoAssemblyChartItem(ctx context.Context, arg InsertIikoAssemblyChartItemParams) error
	InsertIikoPreparedChartItem(ctx context.Context, arg InsertIikoPreparedChartItemParams) error
	LinkTelegramAuthUser(ctx context.Context, arg LinkTelegramAuthUserParams) (AuthUser, error)
	ListAssemblyChartItemsByChartID(ctx context.Context, chartID string) ([]ListAssemblyChartItemsByChartIDRow, error)
	ListAuthUsersByDepartmentID(ctx context.Context, departmentID *int64) ([]AuthUser, error)
	ListDepartments(ctx context.Context, type_ *string) ([]Department, error)
	ListOrderTemplates(ctx context.Context) ([]OrderTemplate, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListPreparedChartItemsByChartID(ctx context.Context, preparedChartID string) ([]ListPreparedChartItemsByChartIDRow, error)
	NextOrderCounter(ctx context.Context, day string) (int64, error)
	UnlinkTelegramAuthUser(ctx context.Context, arg UnlinkTelegramAuthUserParams) error
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpsertIikoAssemblyChart(ctx context.Context, arg UpsertIikoAssemblyChartParams) error
	UpsertIikoPreparedChart(ctx context.Context, arg UpsertIikoPreparedChartParams) error
	UpsertIikoProduct(ctx context.Context, arg UpsertIikoProductParams) error
	UpsertTelegramAuthUserDepartment(ctx context.Context, arg UpsertTelegramAuthUserDepartmentParams) (AuthUser, error)
}

var _ Querier = (*Queries)(nil)
