// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package repo

import (
	"context"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO auth_users (
    telegram_id,
    username,
    role,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
ON CONFLICT(telegram_id) DO UPDATE SET
    username = excluded.username,
    role = excluded.role,
    updated_at = excluded.updated_at
RETURNING id, telegram_id, username, role, created_at, updated_at
`

type CreateAuthUserParams struct {
	TelegramID int64  `json:"telegram_id"`
	Username   string `json:"username"`
	Role       string `json:"role"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, createAuthUser,
		arg.TelegramID,
		arg.Username,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByTelegramID = `-- name: GetAuthUserByTelegramID :one
SELECT id, telegram_id, username, role, created_at, updated_at
FROM auth_users
WHERE telegram_id = ?1
`

func (q *Queries) GetAuthUserByTelegramID(ctx context.Context, telegramID int64) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getAuthUserByTelegramID, telegramID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
