// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"
)

const getGroupByCode = `-- name: GetGroupByCode :one
SELECT code, name
FROM groups
WHERE code = ?1
`

func (q *Queries) GetGroupByCode(ctx context.Context, code string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByCode, code)
	var i Group
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT code, name
FROM groups
ORDER BY name, code
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGroup = `-- name: UpsertGroup :one
INSERT INTO groups (
    code,
    name
) VALUES (
    ?1,
    ?2
)
ON CONFLICT(code) DO UPDATE SET
    name = excluded.name
RETURNING code, name
`

type UpsertGroupParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, upsertGroup, arg.Code, arg.Name)
	var i Group
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}
