// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor.sql

package sqlc

import (
	"context"
)

const getActiveAssemblyChartByProductID = `-- name: GetActiveAssemblyChartByProductID :one
SELECT
    id,
    assembled_product_id,
    assembled_amount,
    date_from,
    date_to
FROM iiko_assembly_charts
WHERE assembled_product_id = ?1
  AND date(date_from) <= date(?2)
  AND (date_to IS NULL OR date(date_to) >= date(?2))
ORDER BY date(date_from) DESC
LIMIT 1
`

type GetActiveAssemblyChartByProductIDParams struct {
	AssembledProductID string      `json:"assembled_product_id"`
	OrderDate          interface{} `json:"order_date"`
}

type GetActiveAssemblyChartByProductIDRow struct {
	ID                 string  `json:"id"`
	AssembledProductID string  `json:"assembled_product_id"`
	AssembledAmount    float64 `json:"assembled_amount"`
	DateFrom           string  `json:"date_from"`
	DateTo             *string `json:"date_to"`
}

func (q *Queries) GetActiveAssemblyChartByProductID(ctx context.Context, arg GetActiveAssemblyChartByProductIDParams) (GetActiveAssemblyChartByProductIDRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveAssemblyChartByProductID, arg.AssembledProductID, arg.OrderDate)
	var i GetActiveAssemblyChartByProductIDRow
	err := row.Scan(
		&i.ID,
		&i.AssembledProductID,
		&i.AssembledAmount,
		&i.DateFrom,
		&i.DateTo,
	)
	return i, err
}

const listAssemblyChartItemsByChartID = `-- name: ListAssemblyChartItemsByChartID :many
SELECT
    i.id AS item_id,
    i.product_id,
    i.amount_out,
    COALESCE(p.name, '') AS product_name,
    COALESCE(p.code, '') AS product_code,
    COALESCE(p.measure_unit, '') AS measure_unit
FROM iiko_assembly_chart_items AS i
LEFT JOIN iiko_products AS p ON p.id = i.product_id
WHERE i.chart_id = ?1
ORDER BY i.sort_weight, i.id
`

type ListAssemblyChartItemsByChartIDRow struct {
	ItemID      string  `json:"item_id"`
	ProductID   string  `json:"product_id"`
	AmountOut   float64 `json:"amount_out"`
	ProductName string  `json:"product_name"`
	ProductCode string  `json:"product_code"`
	MeasureUnit string  `json:"measure_unit"`
}

func (q *Queries) ListAssemblyChartItemsByChartID(ctx context.Context, chartID string) ([]ListAssemblyChartItemsByChartIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssemblyChartItemsByChartID, chartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssemblyChartItemsByChartIDRow
	for rows.Next() {
		var i ListAssemblyChartItemsByChartIDRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ProductID,
			&i.AmountOut,
			&i.ProductName,
			&i.ProductCode,
			&i.MeasureUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
