// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
	"strings"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    number,
    location,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3
)
RETURNING id, number, location, created_at
`

type CreateOrderParams struct {
	Number    string `json:"number"`
	Location  string `json:"location"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.Number, arg.Location, arg.CreatedAt)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderCounterDay = `-- name: CreateOrderCounterDay :exec
INSERT INTO order_counters(day, counter)
VALUES (?1, 0)
ON CONFLICT(day) DO NOTHING
`

func (q *Queries) CreateOrderCounterDay(ctx context.Context, day string) error {
	_, err := q.db.ExecContext(ctx, createOrderCounterDay, day)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    iiko_product_id,
    product_name,
    quantity
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
RETURNING id, order_id, iiko_product_id, product_name, quantity
`

type CreateOrderItemParams struct {
	OrderID       int64   `json:"order_id"`
	IikoProductID *string `json:"iiko_product_id"`
	ProductName   string  `json:"product_name"`
	Quantity      float64 `json:"quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.IikoProductID,
		arg.ProductName,
		arg.Quantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.IikoProductID,
		&i.ProductName,
		&i.Quantity,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, number, location, created_at
FROM orders
WHERE number = ?1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, number string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByNumber, number)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT
    oi.id,
    oi.order_id,
    oi.iiko_product_id,
    oi.product_name,
    oi.quantity,
    COALESCE(p.code, '') AS product_code
FROM order_items AS oi
LEFT JOIN iiko_products AS p ON p.id = oi.iiko_product_id
WHERE oi.order_id = ?1
ORDER BY oi.id
`

type GetOrderItemsByOrderIDRow struct {
	ID            int64   `json:"id"`
	OrderID       int64   `json:"order_id"`
	IikoProductID *string `json:"iiko_product_id"`
	ProductName   string  `json:"product_name"`
	Quantity      float64 `json:"quantity"`
	ProductCode   string  `json:"product_code"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.IikoProductID,
			&i.ProductName,
			&i.Quantity,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderIDs = `-- name: ListOrderItemsByOrderIDs :many
SELECT
    oi.id,
    oi.order_id,
    oi.iiko_product_id,
    oi.product_name,
    oi.quantity,
    COALESCE(p.code, '') AS product_code
FROM order_items AS oi
LEFT JOIN iiko_products AS p ON p.id = oi.iiko_product_id
WHERE oi.order_id IN (/*SLICE:order_ids*/?)
ORDER BY oi.order_id, oi.id
`

type ListOrderItemsByOrderIDsRow struct {
	ID            int64   `json:"id"`
	OrderID       int64   `json:"order_id"`
	IikoProductID *string `json:"iiko_product_id"`
	ProductName   string  `json:"product_name"`
	Quantity      float64 `json:"quantity"`
	ProductCode   string  `json:"product_code"`
}

func (q *Queries) ListOrderItemsByOrderIDs(ctx context.Context, orderIds []int64) ([]ListOrderItemsByOrderIDsRow, error) {
	query := listOrderItemsByOrderIDs
	var queryParams []interface{}
	if len(orderIds) > 0 {
		for _, v := range orderIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:order_ids*/?", strings.Repeat(",?", len(orderIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:order_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsByOrderIDsRow
	for rows.Next() {
		var i ListOrderItemsByOrderIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.IikoProductID,
			&i.ProductName,
			&i.Quantity,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, number, location, created_at
FROM orders
ORDER BY id DESC
LIMIT ?1
`

func (q *Queries) ListOrders(ctx context.Context, limit int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderCounter = `-- name: NextOrderCounter :one
UPDATE order_counters
SET counter = counter + 1
WHERE day = ?1
RETURNING counter
`

func (q *Queries) NextOrderCounter(ctx context.Context, day string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextOrderCounter, day)
	var counter int64
	err := row.Scan(&counter)
	return counter, err
}
