// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateIikoSyncRun(ctx context.Context, arg CreateIikoSyncRunParams) (IikoSyncRun, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderCounterDay(ctx context.Context, day string) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePasswordAuthUser(ctx context.Context, arg CreatePasswordAuthUserParams) (AuthUser, error)
	CreateTelegramAuthUser(ctx context.Context, arg CreateTelegramAuthUserParams) (AuthUser, error)
	DeleteIikoAssemblyChartItemsByChartID(ctx context.Context, chartID string) error
	DeleteIikoPreparedChartItemsByChartID(ctx context.Context, preparedChartID string) error
	DishExistsByCode(ctx context.Context, code string) (int64, error)
	FinishIikoSyncRun(ctx context.Context, arg FinishIikoSyncRunParams) (IikoSyncRun, error)
	GetActiveAssemblyChartByProductID(ctx context.Context, arg GetActiveAssemblyChartByProductIDParams) (GetActiveAssemblyChartByProductIDRow, error)
	GetAuthUserByTelegramID(ctx context.Context, telegramID *int64) (AuthUser, error)
	GetAuthUserByUsername(ctx context.Context, username string) (AuthUser, error)
	GetGroupByCode(ctx context.Context, code string) (Group, error)
	GetIikoProductByCode(ctx context.Context, code string) (GetIikoProductByCodeRow, error)
	GetIikoProductByID(ctx context.Context, id string) (GetIikoProductByIDRow, error)
	GetIikoProductsByName(ctx context.Context, name string) ([]GetIikoProductsByNameRow, error)
	GetOrderByNumber(ctx context.Context, number string) (Order, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error)
	GetProducts(ctx context.Context, type_ *string) ([]GetProductsRow, error)
	GetUserByID(ctx context.Context, id int64) (AuthUser, error)
	InsertIikoAssemblyChartItem(ctx context.Context, arg InsertIikoAssemblyChartItemParams) (IikoAssemblyChartItem, error)
	InsertIikoPreparedChartItem(ctx context.Context, arg InsertIikoPreparedChartItemParams) (IikoPreparedChartItem, error)
	LinkTelegramAuthUser(ctx context.Context, arg LinkTelegramAuthUserParams) (AuthUser, error)
	ListAssemblyChartItemsByChartID(ctx context.Context, chartID string) ([]ListAssemblyChartItemsByChartIDRow, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListIikoProductsByGroupID(ctx context.Context, groupID string) ([]ListIikoProductsByGroupIDRow, error)
	ListOrderItemsByOrderIDs(ctx context.Context, orderIds []int64) ([]OrderItem, error)
	ListOrders(ctx context.Context, limit int64) ([]Order, error)
	NextOrderCounter(ctx context.Context, day string) (int64, error)
	UnlinkTelegramAuthUser(ctx context.Context, arg UnlinkTelegramAuthUserParams) error
	UpsertGroup(ctx context.Context, arg UpsertGroupParams) (Group, error)
	UpsertIikoAssemblyChart(ctx context.Context, arg UpsertIikoAssemblyChartParams) (IikoAssemblyChart, error)
	UpsertIikoPreparedChart(ctx context.Context, arg UpsertIikoPreparedChartParams) (IikoPreparedChart, error)
	UpsertIikoProduct(ctx context.Context, arg UpsertIikoProductParams) (IikoProduct, error)
}

var _ Querier = (*Queries)(nil)
