// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, user_id, name, telegram_chat_id, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, telegram_chat_id, note, created_at, updated_at
`

type CreateClientParams struct {
	ID             uuid.UUID  `json:"id"`
	UserID         *uuid.UUID `json:"user_id"`
	Name           string     `json:"name"`
	TelegramChatID *int64     `json:"telegram_chat_id"`
	Note           *string    `json:"note"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TelegramChatID,
		arg.Note,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TelegramChatID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, user_id, name, telegram_chat_id, note, created_at, updated_at FROM clients WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TelegramChatID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByTelegramChatID = `-- name: GetClientByTelegramChatID :one
SELECT id, user_id, name, telegram_chat_id, note, created_at, updated_at FROM clients WHERE telegram_chat_id = $1
`

func (q *Queries) GetClientByTelegramChatID(ctx context.Context, telegramChatID *int64) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByTelegramChatID, telegramChatID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TelegramChatID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByUserID = `-- name: GetClientByUserID :one
SELECT id, user_id, name, telegram_chat_id, note, created_at, updated_at FROM clients WHERE user_id = $1
`

func (q *Queries) GetClientByUserID(ctx context.Context, userID *uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByUserID, userID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TelegramChatID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, user_id, name, telegram_chat_id, note, created_at, updated_at FROM clients ORDER BY name
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TelegramChatID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = $2,
    telegram_chat_id = $3,
    note = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, telegram_chat_id, note, created_at, updated_at
`

type UpdateClientParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	TelegramChatID *int64    `json:"telegram_chat_id"`
	Note           *string   `json:"note"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.TelegramChatID,
		arg.Note,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TelegramChatID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
