// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (id, iiko_id, name, unit)
VALUES ($1, $2, $3, $4)
RETURNING id, iiko_id, name, unit, created_at, updated_at
`

type CreateIngredientParams struct {
	ID     uuid.UUID `json:"id"`
	IikoID *string   `json:"iiko_id"`
	Name   string    `json:"name"`
	Unit   string    `json:"unit"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.ID,
		arg.IikoID,
		arg.Name,
		arg.Unit,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients WHERE id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIngredient, id)
	return err
}

const getIngredientByID = `-- name: GetIngredientByID :one
SELECT id, iiko_id, name, unit, created_at, updated_at FROM ingredients WHERE id = $1
`

func (q *Queries) GetIngredientByID(ctx context.Context, id uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByID, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredientByIikoID = `-- name: GetIngredientByIikoID :one
SELECT id, iiko_id, name, unit, created_at, updated_at FROM ingredients WHERE iiko_id = $1
`

func (q *Queries) GetIngredientByIikoID(ctx context.Context, iikoID *string) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByIikoID, iikoID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredientByName = `-- name: GetIngredientByName :one
SELECT id, iiko_id, name, unit, created_at, updated_at FROM ingredients WHERE name = $1
`

func (q *Queries) GetIngredientByName(ctx context.Context, name string) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByName, name)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, iiko_id, name, unit, created_at, updated_at FROM ingredients ORDER BY name
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.IikoID,
			&i.Name,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngredientByIikoID = `-- name: UpsertIngredientByIikoID :one
INSERT INTO ingredients (id, iiko_id, name, unit)
VALUES ($1, $2, $3, $4)
ON CONFLICT (iiko_id) DO UPDATE
SET name = EXCLUDED.name,
    unit = EXCLUDED.unit,
    updated_at = now()
RETURNING id, iiko_id, name, unit, created_at, updated_at
`

type UpsertIngredientByIikoIDParams struct {
	ID     uuid.UUID `json:"id"`
	IikoID *string   `json:"iiko_id"`
	Name   string    `json:"name"`
	Unit   string    `json:"unit"`
}

func (q *Queries) UpsertIngredientByIikoID(ctx context.Context, arg UpsertIngredientByIikoIDParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, upsertIngredientByIikoID,
		arg.ID,
		arg.IikoID,
		arg.Name,
		arg.Unit,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
