// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kitchens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createKitchen = `-- name: CreateKitchen :one
INSERT INTO kitchens (id, user_id, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateKitchenParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
	Name   string     `json:"name"`
}

func (q *Queries) CreateKitchen(ctx context.Context, arg CreateKitchenParams) (Kitchen, error) {
	row := q.db.QueryRow(ctx, createKitchen, arg.ID, arg.UserID, arg.Name)
	var i Kitchen
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKitchen = `-- name: DeleteKitchen :exec
DELETE FROM kitchens WHERE id = $1
`

func (q *Queries) DeleteKitchen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteKitchen, id)
	return err
}

const getKitchenByID = `-- name: GetKitchenByID :one
SELECT id, user_id, name, created_at, updated_at FROM kitchens WHERE id = $1
`

func (q *Queries) GetKitchenByID(ctx context.Context, id uuid.UUID) (Kitchen, error) {
	row := q.db.QueryRow(ctx, getKitchenByID, id)
	var i Kitchen
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKitchenByUserID = `-- name: GetKitchenByUserID :one
SELECT id, user_id, name, created_at, updated_at FROM kitchens WHERE user_id = $1
`

func (q *Queries) GetKitchenByUserID(ctx context.Context, userID *uuid.UUID) (Kitchen, error) {
	row := q.db.QueryRow(ctx, getKitchenByUserID, userID)
	var i Kitchen
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKitchens = `-- name: ListKitchens :many
SELECT id, user_id, name, created_at, updated_at FROM kitchens ORDER BY name
`

func (q *Queries) ListKitchens(ctx context.Context) ([]Kitchen, error) {
	rows, err := q.db.Query(ctx, listKitchens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kitchen{}
	for rows.Next() {
		var i Kitchen
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKitchen = `-- name: UpdateKitchen :one
UPDATE kitchens
SET name = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, created_at, updated_at
`

type UpdateKitchenParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateKitchen(ctx context.Context, arg UpdateKitchenParams) (Kitchen, error) {
	row := q.db.QueryRow(ctx, updateKitchen, arg.ID, arg.Name)
	var i Kitchen
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
