// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Client struct {
	ID             uuid.UUID  `json:"id"`
	UserID         *uuid.UUID `json:"user_id"`
	Name           string     `json:"name"`
	TelegramChatID *int64     `json:"telegram_chat_id"`
	Note           *string    `json:"note"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type Ingredient struct {
	ID        uuid.UUID `json:"id"`
	IikoID    *string   `json:"iiko_id"`
	Name      string    `json:"name"`
	Unit      string    `json:"unit"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Kitchen struct {
	ID        uuid.UUID  `json:"id"`
	UserID    *uuid.UUID `json:"user_id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type Order struct {
	ID                uuid.UUID  `json:"id"`
	ClientID          uuid.UUID  `json:"client_id"`
	KitchenID         *uuid.UUID `json:"kitchen_id"`
	TelegramChatID    *int64     `json:"telegram_chat_id"`
	TelegramMessageID *int64     `json:"telegram_message_id"`
	OrderDate         time.Time  `json:"order_date"`
	Status            string     `json:"status"`
	RawText           *string    `json:"raw_text"`
	Note              *string    `json:"note"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

type OrderItem struct {
	ID        uuid.UUID `json:"id"`
	OrderID   uuid.UUID `json:"order_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  float64   `json:"quantity"`
	Unit      string    `json:"unit"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Product struct {
	ID        uuid.UUID `json:"id"`
	IikoID    *string   `json:"iiko_id"`
	Name      string    `json:"name"`
	Unit      string    `json:"unit"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TechCard struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	YieldQty  float64   `json:"yield_qty"`
	YieldUnit string    `json:"yield_unit"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TechCardItem struct {
	ID           uuid.UUID  `json:"id"`
	TechCardID   uuid.UUID  `json:"tech_card_id"`
	IngredientID *uuid.UUID `json:"ingredient_id"`
	SubProductID *uuid.UUID `json:"sub_product_id"`
	GrossQty     float64    `json:"gross_qty"`
	NetQty       float64    `json:"net_qty"`
	Unit         string     `json:"unit"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Login        string    `json:"login"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
