// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id, client_id, kitchen_id, telegram_chat_id, telegram_message_id,
    order_date, status, raw_text, note
) VALUES ($1, $2, $3, $4, $5, $6, COALESCE($9::text, 'new'), $7, $8)
RETURNING id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at
`

type CreateOrderParams struct {
	ID                uuid.UUID  `json:"id"`
	ClientID          uuid.UUID  `json:"client_id"`
	KitchenID         *uuid.UUID `json:"kitchen_id"`
	TelegramChatID    *int64     `json:"telegram_chat_id"`
	TelegramMessageID *int64     `json:"telegram_message_id"`
	OrderDate         time.Time  `json:"order_date"`
	RawText           *string    `json:"raw_text"`
	Note              *string    `json:"note"`
	Status            *string    `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.ClientID,
		arg.KitchenID,
		arg.TelegramChatID,
		arg.TelegramMessageID,
		arg.OrderDate,
		arg.RawText,
		arg.Note,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.KitchenID,
		&i.TelegramChatID,
		&i.TelegramMessageID,
		&i.OrderDate,
		&i.Status,
		&i.RawText,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, order_id, product_id, quantity, unit)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, quantity, unit, created_at, updated_at
`

type CreateOrderItemParams struct {
	ID        uuid.UUID `json:"id"`
	OrderID   uuid.UUID `json:"order_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  float64   `json:"quantity"`
	Unit      string    `json:"unit"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Unit,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const deleteOrderItems = `-- name: DeleteOrderItems :exec
DELETE FROM order_items WHERE order_id = $1
`

func (q *Queries) DeleteOrderItems(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderItems, orderID)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.KitchenID,
		&i.TelegramChatID,
		&i.TelegramMessageID,
		&i.OrderDate,
		&i.Status,
		&i.RawText,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, quantity, unit, created_at, updated_at FROM order_items
WHERE order_id = $1
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at FROM orders
WHERE ($1::text IS NULL OR status = $1::text)
ORDER BY order_date DESC, created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context, status *string) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.KitchenID,
			&i.TelegramChatID,
			&i.TelegramMessageID,
			&i.OrderDate,
			&i.Status,
			&i.RawText,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByClient = `-- name: ListOrdersByClient :many
SELECT id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at FROM orders
WHERE client_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY order_date DESC, created_at DESC
`

type ListOrdersByClientParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Status   *string   `json:"status"`
}

func (q *Queries) ListOrdersByClient(ctx context.Context, arg ListOrdersByClientParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByClient, arg.ClientID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.KitchenID,
			&i.TelegramChatID,
			&i.TelegramMessageID,
			&i.OrderDate,
			&i.Status,
			&i.RawText,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByDate = `-- name: ListOrdersByDate :many
SELECT id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at FROM orders
WHERE order_date = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC
`

type ListOrdersByDateParams struct {
	OrderDate time.Time `json:"order_date"`
	Status    *string   `json:"status"`
}

func (q *Queries) ListOrdersByDate(ctx context.Context, arg ListOrdersByDateParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByDate, arg.OrderDate, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.KitchenID,
			&i.TelegramChatID,
			&i.TelegramMessageID,
			&i.OrderDate,
			&i.Status,
			&i.RawText,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByDateRange = `-- name: ListOrdersByDateRange :many
SELECT id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at FROM orders
WHERE order_date BETWEEN $1 AND $2
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY order_date, created_at
`

type ListOrdersByDateRangeParams struct {
	OrderDate   time.Time `json:"order_date"`
	OrderDate_2 time.Time `json:"order_date_2"`
	Status      *string   `json:"status"`
}

func (q *Queries) ListOrdersByDateRange(ctx context.Context, arg ListOrdersByDateRangeParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByDateRange, arg.OrderDate, arg.OrderDate_2, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.KitchenID,
			&i.TelegramChatID,
			&i.TelegramMessageID,
			&i.OrderDate,
			&i.Status,
			&i.RawText,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByKitchen = `-- name: ListOrdersByKitchen :many
SELECT id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at FROM orders
WHERE kitchen_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY order_date DESC, created_at DESC
`

type ListOrdersByKitchenParams struct {
	KitchenID *uuid.UUID `json:"kitchen_id"`
	Status    *string    `json:"status"`
}

func (q *Queries) ListOrdersByKitchen(ctx context.Context, arg ListOrdersByKitchenParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByKitchen, arg.KitchenID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.KitchenID,
			&i.TelegramChatID,
			&i.TelegramMessageID,
			&i.OrderDate,
			&i.Status,
			&i.RawText,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET kitchen_id = $2,
    order_date = $3,
    status = $4,
    note = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at
`

type UpdateOrderParams struct {
	ID        uuid.UUID  `json:"id"`
	KitchenID *uuid.UUID `json:"kitchen_id"`
	OrderDate time.Time  `json:"order_date"`
	Status    string     `json:"status"`
	Note      *string    `json:"note"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.KitchenID,
		arg.OrderDate,
		arg.Status,
		arg.Note,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.KitchenID,
		&i.TelegramChatID,
		&i.TelegramMessageID,
		&i.OrderDate,
		&i.Status,
		&i.RawText,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, client_id, kitchen_id, telegram_chat_id, telegram_message_id, order_date, status, raw_text, note, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.KitchenID,
		&i.TelegramChatID,
		&i.TelegramMessageID,
		&i.OrderDate,
		&i.Status,
		&i.RawText,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
