// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, iiko_id, name, unit)
VALUES ($1, $2, $3, $4)
RETURNING id, iiko_id, name, unit, created_at, updated_at
`

type CreateProductParams struct {
	ID     uuid.UUID `json:"id"`
	IikoID *string   `json:"iiko_id"`
	Name   string    `json:"name"`
	Unit   string    `json:"unit"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.IikoID,
		arg.Name,
		arg.Unit,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, iiko_id, name, unit, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByIikoID = `-- name: GetProductByIikoID :one
SELECT id, iiko_id, name, unit, created_at, updated_at FROM products WHERE iiko_id = $1
`

func (q *Queries) GetProductByIikoID(ctx context.Context, iikoID *string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByIikoID, iikoID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, iiko_id, name, unit, created_at, updated_at FROM products WHERE name = $1
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, iiko_id, name, unit, created_at, updated_at FROM products ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.IikoID,
			&i.Name,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProductByIikoID = `-- name: UpsertProductByIikoID :one
INSERT INTO products (id, iiko_id, name, unit)
VALUES ($1, $2, $3, $4)
ON CONFLICT (iiko_id) DO UPDATE
SET name = EXCLUDED.name,
    unit = EXCLUDED.unit,
    updated_at = now()
RETURNING id, iiko_id, name, unit, created_at, updated_at
`

type UpsertProductByIikoIDParams struct {
	ID     uuid.UUID `json:"id"`
	IikoID *string   `json:"iiko_id"`
	Name   string    `json:"name"`
	Unit   string    `json:"unit"`
}

func (q *Queries) UpsertProductByIikoID(ctx context.Context, arg UpsertProductByIikoIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProductByIikoID,
		arg.ID,
		arg.IikoID,
		arg.Name,
		arg.Unit,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.IikoID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
