// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error)
	CreateKitchen(ctx context.Context, arg CreateKitchenParams) (Kitchen, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateTechCard(ctx context.Context, arg CreateTechCardParams) (TechCard, error)
	CreateTechCardItem(ctx context.Context, arg CreateTechCardItemParams) (TechCardItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteClient(ctx context.Context, id uuid.UUID) error
	DeleteIngredient(ctx context.Context, id uuid.UUID) error
	DeleteKitchen(ctx context.Context, id uuid.UUID) error
	DeleteOrder(ctx context.Context, id uuid.UUID) error
	DeleteOrderItems(ctx context.Context, orderID uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteTechCard(ctx context.Context, id uuid.UUID) error
	DeleteTechCardItems(ctx context.Context, techCardID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	GetClientByTelegramChatID(ctx context.Context, telegramChatID *int64) (Client, error)
	GetClientByUserID(ctx context.Context, userID *uuid.UUID) (Client, error)
	GetIngredientByID(ctx context.Context, id uuid.UUID) (Ingredient, error)
	GetIngredientByIikoID(ctx context.Context, iikoID *string) (Ingredient, error)
	GetIngredientByName(ctx context.Context, name string) (Ingredient, error)
	GetKitchenByID(ctx context.Context, id uuid.UUID) (Kitchen, error)
	GetKitchenByUserID(ctx context.Context, userID *uuid.UUID) (Kitchen, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductByIikoID(ctx context.Context, iikoID *string) (Product, error)
	GetProductByName(ctx context.Context, name string) (Product, error)
	GetTechCardByID(ctx context.Context, id uuid.UUID) (TechCard, error)
	GetTechCardByProductID(ctx context.Context, productID uuid.UUID) (TechCard, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListIngredients(ctx context.Context) ([]Ingredient, error)
	ListKitchens(ctx context.Context) ([]Kitchen, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrders(ctx context.Context, status *string) ([]Order, error)
	ListOrdersByClient(ctx context.Context, arg ListOrdersByClientParams) ([]Order, error)
	ListOrdersByDate(ctx context.Context, arg ListOrdersByDateParams) ([]Order, error)
	ListOrdersByDateRange(ctx context.Context, arg ListOrdersByDateRangeParams) ([]Order, error)
	ListOrdersByKitchen(ctx context.Context, arg ListOrdersByKitchenParams) ([]Order, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListTechCardItems(ctx context.Context, techCardID uuid.UUID) ([]TechCardItem, error)
	ListTechCards(ctx context.Context) ([]TechCard, error)
	ListTechCardsByProductID(ctx context.Context, productID uuid.UUID) ([]TechCard, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateKitchen(ctx context.Context, arg UpdateKitchenParams) (Kitchen, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateTechCard(ctx context.Context, arg UpdateTechCardParams) (TechCard, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpsertIngredientByIikoID(ctx context.Context, arg UpsertIngredientByIikoIDParams) (Ingredient, error)
	UpsertProductByIikoID(ctx context.Context, arg UpsertProductByIikoIDParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
