// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tech_cards.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTechCard = `-- name: CreateTechCard :one
INSERT INTO tech_cards (id, product_id, yield_qty, yield_unit)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, yield_qty, yield_unit, created_at, updated_at
`

type CreateTechCardParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	YieldQty  float64   `json:"yield_qty"`
	YieldUnit string    `json:"yield_unit"`
}

func (q *Queries) CreateTechCard(ctx context.Context, arg CreateTechCardParams) (TechCard, error) {
	row := q.db.QueryRow(ctx, createTechCard,
		arg.ID,
		arg.ProductID,
		arg.YieldQty,
		arg.YieldUnit,
	)
	var i TechCard
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.YieldQty,
		&i.YieldUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTechCardItem = `-- name: CreateTechCardItem :one
INSERT INTO tech_card_items (
    id, tech_card_id, ingredient_id, sub_product_id, gross_qty, net_qty, unit
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tech_card_id, ingredient_id, sub_product_id, gross_qty, net_qty, unit, created_at, updated_at
`

type CreateTechCardItemParams struct {
	ID           uuid.UUID  `json:"id"`
	TechCardID   uuid.UUID  `json:"tech_card_id"`
	IngredientID *uuid.UUID `json:"ingredient_id"`
	SubProductID *uuid.UUID `json:"sub_product_id"`
	GrossQty     float64    `json:"gross_qty"`
	NetQty       float64    `json:"net_qty"`
	Unit         string     `json:"unit"`
}

func (q *Queries) CreateTechCardItem(ctx context.Context, arg CreateTechCardItemParams) (TechCardItem, error) {
	row := q.db.QueryRow(ctx, createTechCardItem,
		arg.ID,
		arg.TechCardID,
		arg.IngredientID,
		arg.SubProductID,
		arg.GrossQty,
		arg.NetQty,
		arg.Unit,
	)
	var i TechCardItem
	err := row.Scan(
		&i.ID,
		&i.TechCardID,
		&i.IngredientID,
		&i.SubProductID,
		&i.GrossQty,
		&i.NetQty,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTechCard = `-- name: DeleteTechCard :exec
DELETE FROM tech_cards WHERE id = $1
`

func (q *Queries) DeleteTechCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTechCard, id)
	return err
}

const deleteTechCardItems = `-- name: DeleteTechCardItems :exec
DELETE FROM tech_card_items WHERE tech_card_id = $1
`

func (q *Queries) DeleteTechCardItems(ctx context.Context, techCardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTechCardItems, techCardID)
	return err
}

const getTechCardByID = `-- name: GetTechCardByID :one
SELECT id, product_id, yield_qty, yield_unit, created_at, updated_at FROM tech_cards WHERE id = $1
`

func (q *Queries) GetTechCardByID(ctx context.Context, id uuid.UUID) (TechCard, error) {
	row := q.db.QueryRow(ctx, getTechCardByID, id)
	var i TechCard
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.YieldQty,
		&i.YieldUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechCardByProductID = `-- name: GetTechCardByProductID :one
SELECT id, product_id, yield_qty, yield_unit, created_at, updated_at FROM tech_cards
WHERE product_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetTechCardByProductID(ctx context.Context, productID uuid.UUID) (TechCard, error) {
	row := q.db.QueryRow(ctx, getTechCardByProductID, productID)
	var i TechCard
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.YieldQty,
		&i.YieldUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTechCardItems = `-- name: ListTechCardItems :many
SELECT id, tech_card_id, ingredient_id, sub_product_id, gross_qty, net_qty, unit, created_at, updated_at FROM tech_card_items
WHERE tech_card_id = $1
`

func (q *Queries) ListTechCardItems(ctx context.Context, techCardID uuid.UUID) ([]TechCardItem, error) {
	rows, err := q.db.Query(ctx, listTechCardItems, techCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TechCardItem{}
	for rows.Next() {
		var i TechCardItem
		if err := rows.Scan(
			&i.ID,
			&i.TechCardID,
			&i.IngredientID,
			&i.SubProductID,
			&i.GrossQty,
			&i.NetQty,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTechCards = `-- name: ListTechCards :many
SELECT id, product_id, yield_qty, yield_unit, created_at, updated_at FROM tech_cards ORDER BY created_at DESC
`

func (q *Queries) ListTechCards(ctx context.Context) ([]TechCard, error) {
	rows, err := q.db.Query(ctx, listTechCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TechCard{}
	for rows.Next() {
		var i TechCard
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.YieldQty,
			&i.YieldUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTechCardsByProductID = `-- name: ListTechCardsByProductID :many
SELECT id, product_id, yield_qty, yield_unit, created_at, updated_at FROM tech_cards
WHERE product_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTechCardsByProductID(ctx context.Context, productID uuid.UUID) ([]TechCard, error) {
	rows, err := q.db.Query(ctx, listTechCardsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TechCard{}
	for rows.Next() {
		var i TechCard
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.YieldQty,
			&i.YieldUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTechCard = `-- name: UpdateTechCard :one
UPDATE tech_cards
SET yield_qty = $2,
    yield_unit = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, yield_qty, yield_unit, created_at, updated_at
`

type UpdateTechCardParams struct {
	ID        uuid.UUID `json:"id"`
	YieldQty  float64   `json:"yield_qty"`
	YieldUnit string    `json:"yield_unit"`
}

func (q *Queries) UpdateTechCard(ctx context.Context, arg UpdateTechCardParams) (TechCard, error) {
	row := q.db.QueryRow(ctx, updateTechCard, arg.ID, arg.YieldQty, arg.YieldUnit)
	var i TechCard
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.YieldQty,
		&i.YieldUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
